// AUTO-GENERATED by scripts/build-blog.ts — do not edit manually
import type { BlogPost } from "@/data/models/BlogPost";

export const blogPosts: BlogPost[] = [
  {
    slug: "hello-world",
    title: "Hello World!: The first blog post",
    date: "2026-03-30",
    description: "The first post on my blog, detailing how it's built.",
    tags: ["web", "dev", "blog"],
    coverImage: undefined,
    draft: false,
    content: `
I've been meaning to get around to writing a proper blog at some point, for things like:

- Technical articles on things I've learned about or recently implemented
- Opinion pieces on things I've thought about
- Anything else I want to write about and publish on my website

## How the blog is built

This blog is in the same project as my portfolio site for consistent styling and theming, I debated a separate project and allowing for \`blog.yaqinhasan.com\` to work, but I decided against it for the maintenance overhead.

- **Vue & TypeScript & Vite SSG & Tailwind CSS** for the UI, this is the same stuff the site is built with. SSG is so that everything is pre-rendered to HTML for SEO and GEO.
- **Markdown** files for simple authoring of the blog posts, I just write portable \`.md\` files and the build system handles the rest. Also makes it really easy to port these files to different platforms.

### Code Highlighting

The blog supports theme-aware syntax highlighting out of the box:

\`\`\`typescript
const greeting = (name: string): string => \`Hello, \${name}! Welcome to the blog.\`;

console.log(greeting("World"));
\`\`\`

\`\`\`python
def fibonacci(n: int) -> list[int]:
    """Generate the first n Fibonacci numbers."""
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[i-1] + fib[i-2])
    return fib[:n]

print(fibonacci(10))
\`\`\`

### Embedded Content (Images)

You can embed saved images from the \`content/blog/images/..\` directory using standard md embedding syntax:

![image](/content/blog/images/coconut.jpg)

Or you can use a url for online images (this is the same image, just served from the internet):

![image](https://preview.redd.it/this-is-inside-the-tf2-game-files-as-why-v0-vw6c9iwr6rk51.jpg?auto=webp&s=e7afd0eb74dc2572e7c50cee902cda7c140d6a74)

This is the iconic \`coconut.jpg\`, which is load-bearing in the TF2 codebase.

### Embedded Content (Video)

You can embed YouTube videos and other external content directly in posts using standard HTML:

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
  <iframe
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"
    src="https://www.youtube.com/embed/dQw4w9WgXcQ"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
  </iframe>
</div>

More posts coming at some point...
`,
    htmlContent: `<p>I&#39;ve been meaning to get around to writing a proper blog at some point, for things like:</p>
<ul>
<li>Technical articles on things I&#39;ve learned about or recently implemented</li>
<li>Opinion pieces on things I&#39;ve thought about</li>
<li>Anything else I want to write about and publish on my website</li>
</ul>
<h2>How the blog is built</h2>
<p>This blog is in the same project as my portfolio site for consistent styling and theming, I debated a separate project and allowing for <code>blog.yaqinhasan.com</code> to work, but I decided against it for the maintenance overhead.</p>
<ul>
<li><strong>Vue &amp; TypeScript &amp; Vite SSG &amp; Tailwind CSS</strong> for the UI, this is the same stuff the site is built with. SSG is so that everything is pre-rendered to HTML for SEO and GEO.</li>
<li><strong>Markdown</strong> files for simple authoring of the blog posts, I just write portable <code>.md</code> files and the build system handles the rest. Also makes it really easy to port these files to different platforms.</li>
</ul>
<h3>Code Highlighting</h3>
<p>The blog supports theme-aware syntax highlighting out of the box:</p>
<pre class="shiki shiki-themes github-light github-dark" style="--shiki-light:#24292e;--shiki-dark:#e1e4e8;--shiki-light-bg:#fff;--shiki-dark-bg:#24292e" tabindex="0"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">const</span><span style="--shiki-light:#6F42C1;--shiki-dark:#B392F0"> greeting</span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583"> =</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8"> (</span><span style="--shiki-light:#E36209;--shiki-dark:#FFAB70">name</span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">:</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF"> string</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">)</span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">:</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF"> string</span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583"> =></span><span style="--shiki-light:#032F62;--shiki-dark:#9ECBFF"> \`Hello, \${</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">name</span><span style="--shiki-light:#032F62;--shiki-dark:#9ECBFF">}! Welcome to the blog.\`</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">console.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#B392F0">log</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">(</span><span style="--shiki-light:#6F42C1;--shiki-dark:#B392F0">greeting</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">(</span><span style="--shiki-light:#032F62;--shiki-dark:#9ECBFF">"World"</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">));</span></span></code></pre><pre class="shiki shiki-themes github-light github-dark" style="--shiki-light:#24292e;--shiki-dark:#e1e4e8;--shiki-light-bg:#fff;--shiki-dark-bg:#24292e" tabindex="0"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">def</span><span style="--shiki-light:#6F42C1;--shiki-dark:#B392F0"> fibonacci</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">(n: </span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">int</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">) -> list[</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">int</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">]:</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#9ECBFF">    """Generate the first n Fibonacci numbers."""</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">    fib </span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">=</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8"> [</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">0</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">, </span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">1</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">]</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">    for</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8"> i </span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">in</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF"> range</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">(</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">2</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">, n):</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">        fib.append(fib[i</span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">-</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">1</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">] </span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">+</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8"> fib[i</span><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">-</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">2</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">])</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#F97583">    return</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8"> fib[:n]</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">print</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">(fibonacci(</span><span style="--shiki-light:#005CC5;--shiki-dark:#79B8FF">10</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">))</span></span></code></pre><h3>Embedded Content (Images)</h3>
<p>You can embed saved images from the <code>content/blog/images/..</code> directory using standard md embedding syntax:</p>
<p><img src="/content/blog/images/coconut.jpg" alt="image"></p>
<p>Or you can use a url for online images (this is the same image, just served from the internet):</p>
<p><img src="https://preview.redd.it/this-is-inside-the-tf2-game-files-as-why-v0-vw6c9iwr6rk51.jpg?auto=webp&s=e7afd0eb74dc2572e7c50cee902cda7c140d6a74" alt="image"></p>
<p>This is the iconic <code>coconut.jpg</code>, which is load-bearing in the TF2 codebase.</p>
<h3>Embedded Content (Video)</h3>
<p>You can embed YouTube videos and other external content directly in posts using standard HTML:</p>
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
  <iframe
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"
    src="https://www.youtube.com/embed/dQw4w9WgXcQ"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
  </iframe>
</div>

<p>More posts coming at some point...</p>
`,
    readingTime: 2
  }
];

export const allTags: string[] = ["blog", "dev", "web"];

export const blogPostsBySlug: Record<string, BlogPost> = Object.fromEntries(blogPosts.map((p) => [p.slug, p]));
