// AUTO-GENERATED by scripts/sync-github-projects.ts — do not edit manually
// Last synced: 2026-03-21T00:30:31.628Z
import type { GitHubProject } from "@/data/models/Project";

export const githubProjects: GitHubProject[] = [
  {
    id: "CryptIt",
    name: "CryptIt",
    description: "Cryptographically secure secret splitting and reconstruction desktop app",
    htmlDescription: `<h1>CryptIt - File Encryption with Shamir Secret Sharing</h1>
<p>A secure, cross-platform file encryption application built with Tauri, Vue 3, and Rust. CryptIt uses AES-256-GCM encryption combined with Shamir Secret Sharing to provide enterprise-grade security for your sensitive files.</p>
<p><img src="https://img.shields.io/badge/Platform-Windows%20%7C%20macOS%20%7C%20Linux-blue" alt="Platform">
<img src="https://img.shields.io/badge/Rust-1.70+-orange" alt="Rust">
<img src="https://img.shields.io/badge/Vue-3.0+-green" alt="Vue">
<img src="https://img.shields.io/badge/Tauri-2.0+-purple" alt="Tauri"></p>
<h2>🔐 Features</h2>
<h3>Core Functionality</h3>
<ul>
<li><strong>File Encryption/Decryption</strong>: Secure AES-256-GCM encryption for any file type</li>
<li><strong>Shamir Secret Sharing</strong>: Split encryption keys into k-of-n shares for enhanced security</li>
<li><strong>Cross-Platform</strong>: Native desktop app for Windows, macOS, and Linux</li>
<li><strong>Simple UI</strong>: Intuitive interface for selecting files, configuring shares, and managing encryption</li>
</ul>
<h3>Security Features</h3>
<ul>
<li><strong>AES-256-GCM</strong>: Industry-standard encryption with authenticated encryption</li>
<li><strong>Memory Safety</strong>: Rust-powered backend with automatic memory cleanup</li>
<li><strong>No Key Persistence</strong>: Keys are never stored permanently</li>
<li><strong>Secure Random Generation</strong>: Cryptographically secure random number generation</li>
<li><strong>Custom File Format</strong>: Secure <code>.cryptit</code> file format with integrity protection</li>
</ul>
<h2>🏗️ Architecture &amp; Design Decisions</h2>
<h3>Technology Stack</h3>
<ul>
<li><strong>Frontend</strong>: Vue 3 + TypeScript + Vite for reactive UI</li>
<li><strong>Backend</strong>: Rust + Tauri for native performance and security</li>
<li><strong>Crypto</strong>: <code>aes-gcm</code> crate for encryption, <code>shamirs</code> crate for secret sharing</li>
<li><strong>UI</strong>: Native file dialogs via <code>tauri-plugin-dialog</code></li>
</ul>
<h3>Design Decisions</h3>
<ol>
<li><strong>Single Algorithm Focus</strong>: Started with AES-256-GCM for MVP simplicity</li>
<li><strong>Modular Architecture</strong>: Easy to extend with additional algorithms</li>
<li><strong>Secure by Default</strong>: Tauri v2 permissions model for maximum security</li>
<li><strong>Simple File Format</strong>: Custom <code>.cryptit</code> format with nonce and ciphertext</li>
<li><strong>Memory-Safe Operations</strong>: Automatic cleanup of sensitive data</li>
</ol>
<h2>🎯 MVP Constraints</h2>
<p>This MVP was designed to be functional within ~1 hour of development time:</p>
<h3>What&#39;s Included</h3>
<ul>
<li>✅ Single encryption algorithm (AES-256-GCM)</li>
<li>✅ Shamir Secret Sharing with configurable k-of-n thresholds</li>
<li>✅ File and directory selection dialogs</li>
<li>✅ Basic encrypt/decrypt workflow</li>
<li>✅ Share generation and input handling</li>
<li>✅ Cross-platform compatibility</li>
</ul>
<h3>What&#39;s Not Included (Yet)</h3>
<ul>
<li>❌ Multiple encryption algorithms</li>
<li>❌ Batch file processing</li>
<li>❌ Share export to files/QR codes</li>
<li>❌ Progress bars for large files</li>
<li>❌ File metadata preservation</li>
<li>❌ Settings/preferences</li>
<li>❌ Advanced error handling UI</li>
</ul>
<h2>🚀 Future Extensions</h2>
<h3>Planned Features</h3>
<ol>
<li><strong>Multiple Algorithms</strong>: ChaCha20-Poly1305, AES-256-CTR support</li>
<li><strong>Advanced Share Management</strong>:<ul>
<li>Export shares to separate files</li>
<li>QR code generation for shares</li>
<li>Share validation and testing</li>
</ul>
</li>
<li><strong>Enhanced UI/UX</strong>:<ul>
<li>Progress indicators for large files</li>
<li>Drag &amp; drop file selection</li>
<li>Dark/light theme toggle</li>
<li>Batch file processing</li>
</ul>
</li>
<li><strong>Security Enhancements</strong>:<ul>
<li>Hardware security module (HSM) integration</li>
<li>Key derivation from passwords</li>
<li>File integrity verification</li>
</ul>
</li>
<li><strong>Enterprise Features</strong>:<ul>
<li>Audit logging</li>
<li>Policy management</li>
<li>Centralized share storage</li>
</ul>
</li>
</ol>
<h3>Potential Integrations</h3>
<ul>
<li><strong>Cloud Storage</strong>: Secure cloud backup of encrypted files</li>
<li><strong>Password Managers</strong>: Integration with 1Password, Bitwarden</li>
<li><strong>Hardware Tokens</strong>: YubiKey support for additional authentication</li>
<li><strong>Mobile Apps</strong>: React Native companion for share management</li>
</ul>
<h2>🛠️ Development</h2>
<h3>Prerequisites</h3>
<ul>
<li><strong>Node.js</strong> 18+ and npm</li>
<li><strong>Rust</strong> 1.70+</li>
<li><strong>System Dependencies</strong>:<ul>
<li><strong>macOS</strong>: Xcode Command Line Tools</li>
<li><strong>Linux</strong>: <code>build-essential</code>, <code>libwebkit2gtk-4.0-dev</code>, <code>libssl-dev</code></li>
<li><strong>Windows</strong>: Microsoft Visual Studio C++ Build Tools</li>
</ul>
</li>
</ul>
<h3>Setup</h3>
<pre><code class="language-bash"># Clone the repository
git clone &lt;repository-url&gt;
cd CryptIt

# Install dependencies
npm install

# Run development server
npm run tauri dev
</code></pre>
<h3>Development Commands</h3>
<pre><code class="language-bash"># Start development server with hot reload
npm run tauri dev

# Run Rust tests
cd src-tauri &amp;&amp; cargo test

# Run frontend linting
npm run lint

# Type checking
npm run type-check

# Build for development (faster, larger)
npm run tauri build -- --debug
</code></pre>
<h2>📦 Building &amp; Distribution</h2>
<h3>Production Build</h3>
<pre><code class="language-bash"># Build optimized production version
npm run tauri build

# Build with specific target
npm run tauri build -- --target x86_64-pc-windows-msvc

# Build for all platforms (requires setup)
npm run tauri build -- --target universal-apple-darwin
</code></pre>
<h3>Platform-Specific Builds</h3>
<pre><code class="language-bash"># macOS Universal Binary (Intel + Apple Silicon)
npm run tauri build -- --target universal-apple-darwin

# Windows (x64)
npm run tauri build -- --target x86_64-pc-windows-msvc

# Linux (x64)
npm run tauri build -- --target x86_64-unknown-linux-gnu
</code></pre>
<h3>Output Locations</h3>
<ul>
<li><strong>macOS</strong>: <code>src-tauri/target/release/bundle/macos/</code></li>
<li><strong>Windows</strong>: <code>src-tauri/target/release/bundle/msi/</code></li>
<li><strong>Linux</strong>: <code>src-tauri/target/release/bundle/deb/</code> or <code>appimage/</code></li>
</ul>
<h2>🧪 Testing</h2>
<h3>Automated Testing</h3>
<pre><code class="language-bash"># Run all Rust unit tests
cd src-tauri &amp;&amp; cargo test

# Run with verbose output
cd src-tauri &amp;&amp; cargo test -- --nocapture

# Test specific module
cd src-tauri &amp;&amp; cargo test crypto::tests
</code></pre>
<h3>Manual Testing Checklist</h3>
<ul>
<li><input disabled="" type="checkbox"> File encryption with various file types and sizes</li>
<li><input disabled="" type="checkbox"> Share generation with different k-of-n configurations</li>
<li><input disabled="" type="checkbox"> Decryption with minimum required shares</li>
<li><input disabled="" type="checkbox"> Error handling for insufficient shares</li>
<li><input disabled="" type="checkbox"> Cross-platform file dialog functionality</li>
<li><input disabled="" type="checkbox"> Memory usage with large files</li>
</ul>
<h2>📁 Project Structure</h2>
<pre><code>CryptIt/
├── src/                          # Vue frontend
│   ├── App.vue                   # Main application component
│   ├── main.ts                   # Application entry point
│   └── assets/                   # Static assets
├── src-tauri/                    # Rust backend
│   ├── src/
│   │   ├── lib.rs               # Main Tauri application
│   │   ├── crypto.rs            # AES encryption module
│   │   ├── sss.rs              # Shamir Secret Sharing
│   │   └── main.rs              # Application entry point
│   ├── capabilities/
│   │   └── default.json         # Tauri permissions
│   ├── Cargo.toml               # Rust dependencies
│   └── tauri.conf.json          # Tauri configuration
├── .vscode/                      # VSCode configuration
│   ├── launch.json              # Debug configurations
│   ├── settings.json            # Workspace settings
│   └── extensions.json          # Recommended extensions
├── package.json                  # Node.js dependencies
└── README.md                     # This file
</code></pre>
<h2>🔧 Debugging</h2>
<h3>Frontend Debugging</h3>
<pre><code class="language-bash"># Open browser dev tools in the app
# Right-click → &quot;Inspect Element&quot; or press F12

# Check console for JavaScript errors
# Network tab for Tauri command failures
</code></pre>
<h3>Backend Debugging</h3>
<pre><code class="language-bash"># Run with debug logging
RUST_LOG=debug npm run tauri dev

# Run with application-specific logs
RUST_LOG=cryptit=debug npm run tauri dev

# Enable backtraces for panics
RUST_BACKTRACE=1 npm run tauri dev
</code></pre>
<h3>VSCode Debugging</h3>
<ol>
<li>Install recommended extensions (see <code>.vscode/extensions.json</code>)</li>
<li>Use provided debug configurations in <code>.vscode/launch.json</code></li>
<li>Set breakpoints in both Rust and TypeScript code</li>
<li>Run &quot;Tauri Development Debug&quot; configuration</li>
</ol>
<h2>🔒 Security Considerations</h2>
<h3>Implemented Security Measures</h3>
<ul>
<li><strong>Memory Safety</strong>: Automatic cleanup of encryption keys</li>
<li><strong>Secure Random Generation</strong>: CSPRNG for all cryptographic operations</li>
<li><strong>Constant-Time Operations</strong>: Resistant to timing attacks</li>
<li><strong>No Key Storage</strong>: Keys exist only in memory during operations</li>
<li><strong>Tauri Security Model</strong>: Granular permissions for system access</li>
</ul>
<h3>Security Best Practices</h3>
<ul>
<li>Always verify share authenticity before decryption</li>
<li>Store shares in separate, secure locations</li>
<li>Use strong physical security for share storage</li>
<li>Regularly test decryption process with backup shares</li>
<li>Keep the application updated for security patches</li>
</ul>
<h2>📄 License</h2>
<p>This project is licensed under the MIT License - see the <a href="https://github.com/yaq1n0/CryptIt/blob/main/LICENSE">LICENSE</a> file for details.</p>
<h2>🤝 Contributing</h2>
<p>Contributions are welcome! Please read our contributing guidelines and submit pull requests for any improvements.</p>
<h3>Development Workflow</h3>
<ol>
<li>Fork the repository</li>
<li>Create a feature branch (<code>git checkout -b feature/amazing-feature</code>)</li>
<li>Make your changes</li>
<li>Run tests (<code>cargo test</code> and manual testing)</li>
<li>Commit your changes (<code>git commit -m &#39;Add amazing feature&#39;</code>)</li>
<li>Push to the branch (<code>git push origin feature/amazing-feature</code>)</li>
<li>Open a Pull Request</li>
</ol>
<hr>
<p><strong>Built with ❤️ using Rust, Vue, and Tauri</strong></p>
`,
    url: "https://github.com/yaq1n0/CryptIt",
    language: "Rust",
    topics: [],
    archived: false,
    createdAt: "2025-07-26T18:38:17Z",
    updatedAt: "2026-03-20T21:17:43Z"
  },
  {
    id: "CyberVehiclesOverhaul-2.1PL",
    name: "CyberVehiclesOverhaul-2.1PL",
    description: "CyberVehiclesOverhaul fork supporting Phantom Liberty Vehicles & version 2.1",
    htmlDescription: `<h1>An extension to the <a href="https://www.nexusmods.com/cyberpunk2077/mods/3016">Cyber Vehicles Overhaul</a> mod by Erok</h1>
<p>This was initially made when the original mod didn&#39;t support Phantom Liberty and 2.1 vehicles, as well as to experiment with game modding further. 
Has since been abandoned as the mod now natively supports these vehicles</p>
</br>

<h3>Accurate Speedometer</h3>
<p>Using <a href="https://www.nexusmods.com/cyberpunk2077/mods/5387">Accurate Speedometer</a> mod is recommended so that the tuned speeds are more realistic. Although NPCs will still drive at &quot;40mph&quot; (or an adjusted realistic ~25mph). </br></p>
<h3>Notes</h3>
<p>Cyber Engine Tweaks vehicle system <a href="https://wiki.redmodding.org/cyber-engine-tweaks/functions/systems/vehiclesystem">documentation</a> \\</p>
<p>List of <a href="https://cyberpunk.fandom.com/wiki/Cyberpunk_2077_Vehicles">vehicles</a> in Cyberpunk Wiki </p>
<h3>Existing vehicles with new variants:</h3>
<p>for these, the existing tweak files can be modified to account for the new variations</p>
<pre><code>Arch Nazare (Vehicle.v_sportbike2_arch_player)
Arch Nazare Racer (Vehicle.v_sportbike2_arch_player_02?)
Arch Nazare Kobold (Vehicle.v_sportbike2_arch_player_03?)
Arch Nazare Itsumade (Vehicle.v_sportbike2_arch_tyger_player?)
Jackie&#39;s Arch (Vehicle.v_sportbike2_arch_jackie_player, Vehicle.v_sportbike2_arch_jackie_tuned_player)
Malina-mobile (Vehicle.v_sportbike2_arch_linas_player?)

Yaiba Kusanagi CT-3X (Vehicle.v_sportbike1_yaiba_kusanagi_player?)
Yaiba Kusanagi Akashita (Vehicle.v_sportbike1_yaiba_kusanagi_player_02?)
Yaiba Kusanagi Peacekeeper (Vehicle.v_sportbike1_yaiba_kusanagi_player_03?)
UNKNOWN? (Vehicle.v_sportbike1_yaiba_kusanagi__tyger_player?)
    
Archer Quartz Bandit (Vehicle.v_standard2_archer_quartz_nomad_player?)
Archer Quartz Specter (Vehicle.v_standard2_archer_quartz_nomad_player_02?)

Brennan Apollo (Vehicle.v_sportbike3_brennan_apollo_player)
Brennan Apollo 650-S (Vehicle.v_sportbike3_brennan_apollo_player_02??)

Herrera Outlaw GTS (Vehicle.v_sport1_herrera_outlaw_player) [DONE]
Herrera Outlaw Weiler (Vehicle.v_sport1_herrera_outlaw_heist_player) [DONE]

Mahir Supron FS3 (Vehicle.v_standard3_mahir_supron_player)
Mahir Supron Trailbruiser (Vehicle.v_standard3_mahir_supron_kurtz_player)

Mizutani Shion (Vehicle.v_sport2_mizutani_shion_player) [DONE]
Mizutani Shion Coyote (Vehicle.v_sport2_mizutani_shion_nomad_player?) [DONE?]
Mizutani Shion Samum (Vehicle.v_sport2_mizutani_shion_nomad_02_player??)

Porshe 911 Turbo (Vehicle.v_sport2_porsche_911turbo_player)
Porshe 911 Turbo Cabriolet (Vehicle.v_sport2_porsche_911turbo_cabrio_player)

Quadra Type-66 
Quadra Type-66 Wingate
Quadra Type-66 Hoon

// Type66&#39;s should be one of these
(Vehicle.v_sport2_quadra_type66_player)
(Vehicle.v_sport2_quadra_type66_02_player)
(Vehicle.v_sport2_quadra_type66_ncu_player)
(Vehicle.v_sport2_quadra_type66_nomad_player)
(Vehicle.v_sport2_quadra_type66_nomad_player_03)
(Vehicle.v_sport2_quadra_type66_avenger_player)

Thorton Colby
Thorton Colby Barghest
Thorton Colby Vulture

Thorton Galena
Thorton Galena Locust
</code></pre>
<h3>Entirely new vehicles:</h3>
<p>for these, new tweak files will need to be created from TweakDB data</p>
<pre><code>Herrera Riptide GT2 (Vehicle.v_sport1_herrera_riptide_player?)
Herrera Riptide Terrier (Vehicle.v_sport1_herrera_riptide_terrier?)

Makigai Tanishi T400 (Vehicle.v_standard3_makigai_tanishi_player? mrhands?)
Makigai Tanishi Kuma (Vehicle.v_standard3_makigai_tanishi_kuma?)

Militech Hellhound (Vehicle.v_standard3_militech_hellhound_player)

Mizutani Hozuki MH2 
Mizutani Hozuki Hoseki (Vehicle.v_standard2_mizutani_hozuki_player)

Quadra Sport R-7 
Quadra Sport R-7 Charon 
Quadra Sport R-7 Sterling 
Quadra Sport R-7 Chiaroscuro 
Quadra Sport R-7 Vigilante 

// Sport R-7&#39;s should be one of these
(Vehicle.v_sport1_quadra_sport_r7_mrhands)
(Vehicle.v_sport1_quadra_sport_r7_netrunner)
(Vehicle.v_sport1_quadra_sport_r7_netrunner_01)
(Vehicle.v_sport1_quadra_sport_r7_netrunner_02)
(Vehicle.v_sport1_quadra_sport_r7_player)
(Vehicle.v_sport1_quadra_sport_r7_player_02)

Thorton Merrimac
Thorton Merrimac Warlock
</code></pre>
<h3>Changelog</h3>
<ul>
<li>Sped up the Herrera Outlaw, made the Weiler variation actually a tuned up version</li>
</ul>
`,
    url: "https://github.com/yaq1n0/CyberVehiclesOverhaul-2.1PL",
    language: "Lua",
    topics: [],
    archived: false,
    createdAt: "2023-12-30T03:46:38Z",
    updatedAt: "2026-03-20T20:59:21Z"
  },
  {
    id: "DegreeArchive",
    name: "DegreeArchive",
    description: "Various projects from my undergrad",
    htmlDescription: `<h1>Degree Archive</h1>
<p>Projects that were noteworthy enough to be mentioned but not self-contained or large enough to have their own repository. </p>
<h1>Why not just upload the entire backup of all the files related to my degree?</h1>
<p>I initially thought about just uploading my entire degree archive as-is but decided against this for several reasons. </p>
<ul>
<li>It&#39;s organized by year then by module and that&#39;s about it, there&#39;s everything from revision files to lecture slides in there and not all of it is code. </li>
<li>It contains private information or proprietary code that I am not allowed to publish on GitHub</li>
<li>It contains exam/assessment solutions that I am not allowed to publish on GitHub.</li>
</ul>
<h1>So what&#39;s in this repository?</h1>
<p>After realizing that no one would bother sifting through 3 years worth of data, I decided to sift through it myself and select the parts I wanted to highlight. </p>
<p>Following this I organized and sanitized the data to highlight the skills demonstrated by the completion of these courseworks. </p>
<p>Lastly, I had to go through everything to make sure that nothing the university provided (course specifications etc) was still present and nothing I wasn&#39;t allowed to upload was present (exam/assessment solutions) </p>
<h1>Can I run these files?</h1>
<p>In theory, everything here should work, as they are &quot;submission-ready&quot; but a lot of this is environment-sensitive, meaning that it will take some effort to get it working for any particular environment. </p>
<h1>What exactly is in these folders?</h1>
<p>The folders are named following the schema of <code>&lt;module_name&gt; - &lt;coursework_summary&gt;</code>. The summary should give a general idea of what the project is about and what skills it demonstrates. </p>
`,
    url: "https://github.com/yaq1n0/DegreeArchive",
    language: "Java",
    topics: [],
    archived: false,
    createdAt: "2024-02-27T21:16:01Z",
    updatedAt: "2026-03-20T21:09:51Z"
  },
  {
    id: "DesktopAppTemplate",
    name: "DesktopAppTemplate",
    description: "Template for for quickly creating desktop apps using Python + Tkinter",
    htmlDescription: `<h1>Python 3 Tk based Desktop GUI App template</h1>
<h3>What is this?</h3>
<p>In terms of an MVC design pattern,
The framework includes the skeleton for the &quot;model&quot; and state permanence as well as supporting data structures for this. 
It also includes wrappers to simplify the creation of the UI, or the &quot;view&quot;, and has common control flows implemented (page navigation)
It also includes the logical structure and file structure to support the implementation of the underlying controller code in /lib/app</p>
<h3>Origins</h3>
<p>This was forked from a Python software engineering group coursework I made in my Engineering Foundation Year.
99% of the code is mine as I was the only one who could actually code amongst the engineers.
The source code for the <a href="https://github.com/yaq1n0/rotational-dynamics-python">rotational-dynamics-python</a> coursework
can be found here.</p>
<h3>Seeing Potential</h3>
<p>I saw the potential in repurposing the GUI elements and codebase for the coursework into a template/framework that I
could use in the future.
I eventually want to make it such that I can quickly implement backend functionality separately to the front-end in a
way that is similar to and will be simple to port over to a web-app type deployment with flask.</p>
<h2>Documentation</h2>
<h3>Directory Structure</h3>
<ul>
<li><p>main.py : program entry point</p>
</li>
<li><p>README.md : you are here</p>
</li>
<li><p>/lib : library for everything. </p>
</li>
<li><p>lib/app : your core back-end app code goes here (I suggest using static atomic functions that can be called from the rest of the code)</p>
</li>
<li><p>lib/components : you core front-end app code goes here. Each &quot;Page&quot; of the app has its own class file here. Object instance is used and passed around (Singleton design pattern). </p>
</li>
<li><p>/lib/resources/config : configuration JSONs go here (you can encourage end user editing of these files, but I suggest using the a preference page for this, so that you can sanitize user configurations. )</p>
</li>
<li><p>/lib/resources/images: program image resources go here</p>
</li>
<li><p>/lib/core : contains functions responsible for handling core desktop-app-template functionality (preferences, theming etc. )</p>
</li>
<li><p>/lib/ui : contains all UI elements that can be used (import UI elements from here)</p>
</li>
<li><p>/lib/ui/tk-utils : contains helper functions that simplify repetitive tk actions. </p>
</li>
<li><p>/lib/ui/tk-widgets : contains the Class files for the App versions of the tkinter base widgets</p>
</li>
<li><p>/lib/ui/compound-widgets : contains the Class files for custom compound widgets made from tk-widgets. </p>
</li>
<li><p>/lib/ui/app-widgets : here is where you would put your own custom widgets for your app, if you need them</p>
</li>
</ul>
<h3>imports best practices to prevent circular dependencies</h3>
<ul>
<li>only import as needed, avoid wildcard imports where possible</li>
<li>nothing should be imported into /lib/core</li>
<li>import ui components straight from /lib/ui. Internal import routing should be handled by /lib/ui/<strong>init</strong>.py</li>
</ul>
<h3>How to use (developer)</h3>
<ul>
<li>Use the included DemoPage.py and TemplatePage.py as a start point for creating the UI using the App&#39;s built in widgets</li>
<li>To contribute new AppWidgets, use the App<name> convention to prevent conflicts with Tk&#39;s default widgets.
also try to use polymorphic inheritance from the original Tk widgets.</li>
<li>To contribute new components, use the <name>Page convention</li>
<li>To contribute new functions, use generate_<function> and/or common sense :P</li>
</ul>
<h3>How to use (end-user)</h3>
<ul>
<li>The preferences page should have useful options such as setting the resolution of the program window, and enabling
certain settings.</li>
</ul>
<h2>Features to be added</h2>
<ul>
<li>DemoPage with most of the widgets implemented for demo purposes.</li>
<li>For some reason the program_restart function only works once, I&#39;m assuming it&#39;s some kinda pid issue.
Long term solution might be to remove the need for having to restart the program at all.</li>
</ul>
`,
    url: "https://github.com/yaq1n0/DesktopAppTemplate",
    language: "Python",
    topics: [],
    archived: false,
    createdAt: "2020-05-30T11:04:03Z",
    updatedAt: "2026-03-20T21:10:40Z"
  },
  {
    id: "DownloadBetterGPU",
    name: "DownloadBetterGPU",
    description: "Downloads a better gpu of your choice onto your computer, FREE!",
    htmlDescription: `<h1>🚀 Download Better GPU</h1>
<blockquote>
<p><strong>Warning: This repository contains highly classified quantum GPU transmission technology. Please handle with care.</strong></p>
</blockquote>
<h2>What is this madness?</h2>
<p>Tired of paying $1,500+ for a graphics card that becomes obsolete the moment you buy it? Fed up with waiting 6 months for restocks? Well, wait no more!</p>
<p><strong>Download Better GPU</strong> is the revolutionary solution that lets you download graphics cards directly to your computer through the power of ✨<em>science</em>✨.</p>
<p>Inspired by the legendary <a href="https://downloadmoreram.com/">downloadmoreram.com</a>, this is what happens when a developer gets frustrated with GPU prices and has 30 minutes to spare.</p>
<h2>🎮 Features</h2>
<ul>
<li><strong>Quantum GPU Transmission</strong>: Download RTX 5090s with 32GB GDDR7 straight through your internet connection</li>
<li><strong>Zero Installation</strong>: No screwdrivers required - GPUs materialize in your PCIe 5.0 slot automatically</li>
<li><strong>100% Free</strong>: Why pay $2000+ when you can download for free?</li>
<li><strong>Realistic Progress Bars</strong>: Complete with authentic technical jargon like &quot;Transmitting CUDA/Stream processors...&quot;</li>
<li><strong>Multiple GPU Options</strong>: From budget Intel ARC B580 to ultimate RTX 5090</li>
<li><strong>Mobile Responsive</strong>: Download GPUs on the go!</li>
</ul>
<h2>🛠 Tech Stack</h2>
<p>This cutting-edge application is built with:</p>
<ul>
<li><strong>HTML5</strong>: For structure (obviously)</li>
<li><strong>CSS3</strong>: With gradients so beautiful they&#39;ll make your RTX 5090 weep</li>
<li><strong>Vanilla JavaScript</strong>: No frameworks needed when you have pure quantum physics</li>
<li><strong>GitHub Pages</strong>: Free hosting for free GPU downloads (it&#39;s free all the way down)</li>
</ul>
<h2>🚀 Quick Start</h2>
<ol>
<li>Clone this repository (downloading the repo is free, unlike actual GPUs)</li>
</ol>
<pre><code class="language-bash">git clone https://github.com/yaq1n0/downloadbettergpu.git
</code></pre>
<ol start="2">
<li>Open <code>index.html</code> in your browser</li>
<li>Select your desired GPU</li>
<li>Click download and watch the magic happen</li>
<li><del>Restart your computer</del> (this part actually doesn&#39;t work, sorry)</li>
</ol>
<h2>📊 Download Statistics</h2>
<ul>
<li><strong>Total GPUs Downloaded</strong>: ∞ (limited only by your imagination)</li>
<li><strong>Success Rate</strong>: 100%*</li>
<li><strong>Customer Satisfaction</strong>: 420/69</li>
<li><strong>Actual Hardware Materialized</strong>: 0 (but hey, the animation is smooth!)</li>
</ul>
<p>* <em>Success measured in entertainment value, not actual hardware acquisition</em></p>
<h2>🎯 FAQ</h2>
<p><strong>Q: Does this actually download a GPU to my computer?</strong><br>A: Of course not! This is a joke website. If you could actually download hardware, Intel wouldn&#39;t have needed to make the ARC B580 so affordable.</p>
<p><strong>Q: Why did you make this?</strong><br>A: I was tired of seeing &quot;$1,999 - Out of Stock&quot; on RTX 5090 listings everywhere and decided channeling my frustration into code was healthier than crying.</p>
<p><strong>Q: Can you make one for CPUs?</strong><br>A: Already working on &quot;Download Better CPU&quot; - coming to a GitHub near you!</p>
<p><strong>Q: Is the source code available?</strong><br>A: You&#39;re literally looking at it right now.</p>
<h2>🤝 Contributing</h2>
<p>Found a bug in our quantum transmission algorithm? Want to add support for downloading mining rigs? PRs welcome!</p>
<p>Please ensure your contributions maintain the same level of scientific accuracy (i.e., none whatsoever).</p>
<h2>📜 License</h2>
<p>MIT License - Feel free to fork and create your own hardware download empire.</p>
<h2>🙏 Acknowledgments</h2>
<ul>
<li><strong><a href="https://downloadmoreram.com/">downloadmoreram.com</a></strong> - The OG that inspired this madness</li>
<li><strong>NVIDIA &amp; AMD &amp; Intel</strong> - For making GPUs so expensive that downloading them seems reasonable</li>
<li><strong>Crypto miners</strong> - For making us all collectively lose our minds (again)</li>
<li><strong>AI Datacenters</strong> - For buying up all of TSMC&#39;s wafer capacity</li>
<li><strong>The laws of physics</strong> - Sorry for temporarily ignoring you</li>
</ul>
<h2>⚠️ Disclaimer</h2>
<p>This is a parody website. You cannot actually download physical hardware components over the internet. If this worked, we&#39;d all be rich and GPU shortages would be a thing of the past.</p>
<p>Please buy graphics cards from legitimate retailers (when they&#39;re actually in stock at reasonable prices, which is... still never).</p>
<hr>
<p><strong>Built with ❤️ and frustration by <a href="https://yaqinhasan.com">Yaqin Hasan</a></strong></p>
<p><em>&quot;If you can&#39;t afford it, download it!&quot; - Ancient Proverb (probably)</em></p>
`,
    url: "https://github.com/yaq1n0/DownloadBetterGPU",
    language: "CSS",
    topics: [],
    archived: false,
    createdAt: "2025-07-15T20:02:17Z",
    updatedAt: "2026-03-20T21:17:00Z"
  },
  {
    id: "EloSimulator",
    name: "EloSimulator",
    description: "Elo (and similar) implementation and simulator",
    htmlDescription: `<h1>Elo Simulator</h1>
<p>An implementation of the Elo algorithm and similar ranking algorithms, as well as a simulator environment to find out how quickly these various algorithms find the hidden true elo. </p>
`,
    url: "https://github.com/yaq1n0/EloSimulator",
    language: "Java",
    topics: [],
    archived: false,
    createdAt: "2021-02-25T04:24:56Z",
    updatedAt: "2026-03-20T21:03:04Z"
  },
  {
    id: "FlutterRoboCopy",
    name: "FlutterRoboCopy",
    description: "Flutter GUI for robocopy",
    htmlDescription: `<h1>Flutter RoboCopy</h1>
<p>A flutter project to create a GUI for the windows RoboCopy command. </p>
<p>Done to learn flutter but also to eventually automate/simplify my local network SAMBA NAS backup. </p>
<p>MVP works, but was abandoned as there wasn&#39;t a need for it because I changed my NAS setup. </p>
`,
    url: "https://github.com/yaq1n0/FlutterRoboCopy",
    language: "C++",
    topics: [],
    archived: false,
    createdAt: "2024-01-15T08:35:46Z",
    updatedAt: "2026-03-20T20:57:21Z"
  },
  {
    id: "LinkBlitzer",
    name: "LinkBlitzer",
    description: 'Link bundling, sharing and saving utility, with "open all" functionality. ',
    htmlDescription: `<h1>LinkBlitzer</h1>
<p>Making it simple to share and open bundles of links. Paste links into LinkBlitzer, get one shareable link. Recipients see all shared links and can open them individually, select multiple, or all at once.</p>
<p><strong>Example use cases:</strong> sharing hotel listings with a friend, saving a list of research articles to your bookmarks to reopen them later, grouping together your team onboarding links, creating and saving reading lists, managing your tab routines.</p>
<hr>
<h2>Packages</h2>
<p>This is an npm workspaces monorepo with three packages:</p>
<table>
<thead>
<tr>
<th>Package</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>@linkblitzer/core</code></td>
<td>Encoding/decoding, validation, shared types</td>
</tr>
<tr>
<td><code>@linkblitzer/website</code></td>
<td>Vue 3 SPA — create and view blitz links</td>
</tr>
<tr>
<td><code>@linkblitzer/extension</code></td>
<td>Browser extension — opens links on behalf of the website (bypassing pop-up limitations)</td>
</tr>
</tbody></table>
<hr>
<h2>Core (<code>packages/core</code>)</h2>
<p>Shared library consumed by the website and extension. Does nothing on its own.</p>
<p><strong>What it provides:</strong></p>
<ul>
<li><code>encode(payload)</code> — serializes an array of <code>{ url, notes? }</code> objects to URL-safe Base64</li>
<li><code>decode(encoded)</code> — deserializes and validates with Zod, returns <code>{ ok: true, data }</code> or <code>{ ok: false, error }</code></li>
<li><code>isValidUrl(url)</code> / <code>validateUrls(urls[])</code> — URL validation via the <code>URL</code> constructor</li>
<li>Zod schemas: <code>BlitzUrlSchema</code>, <code>BlitzPayloadSchema</code></li>
<li>Shared message types: <code>MessageOpen</code>, <code>MessageReady</code>, <code>LinkBlitzerMessage</code></li>
</ul>
<p><strong>Commands:</strong></p>
<pre><code class="language-bash">npm run build -w packages/core   # compile TypeScript
npm run test -w packages/core    # run Vitest tests
</code></pre>
<p>Or from the root:</p>
<pre><code class="language-bash">npm run build:core
npm test
</code></pre>
<hr>
<h2>Website (<code>packages/website</code>)</h2>
<p>Vue 3 + Vite SPA with two routes:</p>
<ul>
<li><strong><code>/</code></strong> — Create mode: enter URLs (with optional notes), validate them inline, generate a shareable blitz link</li>
<li><strong><code>/view?shared=...</code></strong> — View mode: decode the link, display URLs with favicons, select and open them</li>
</ul>
<p><strong>Blitz link format:</strong></p>
<pre><code>linkblitzer.com/view?shared={url-safe-base64-encoded-json}
</code></pre>
<p>The JSON is an array of <code>{ url, notes? }</code> objects. Favicons are fetched at view time via Google&#39;s favicon service and are not encoded in the link.</p>
<p><strong>Extension integration:</strong></p>
<p>On mount, the view page listens for a <code>LINKBLITZER:READY</code> postMessage from the extension content script. If the extension is present, &quot;Open selected&quot; sends a <code>LINKBLITZER:OPEN</code> message and the extension handles opening the tabs. If the extension is absent, the page falls back to <code>window.open()</code> — which is blocked on most mobile browsers and some desktop ones when opening many tabs at once.</p>
<p><strong>Dev:</strong></p>
<pre><code class="language-bash">npm run dev:website        # from root
# or
npm run dev -w packages/website
</code></pre>
<p>Runs Vite dev server, typically at <code>http://localhost:5173</code>.</p>
<p><strong>Build:</strong></p>
<pre><code class="language-bash">npm run build:website
# or
npm run build -w packages/website
</code></pre>
<p><strong>Deployment (GitHub Pages — TODO):</strong></p>
<p>The website targets GitHub Pages at <code>linkblitzer.com</code>. Deployment scripts need to be added (e.g. <code>gh-pages</code> npm package or a GitHub Actions workflow that runs <code>vite build</code> and pushes <code>dist/</code> to the <code>gh-pages</code> branch). The Vite config will likely need a <code>base</code> option set if hosted in a subdirectory.</p>
<hr>
<h2>Extension (<code>packages/extension</code>)</h2>
<p>A minimal browser extension built with <a href="https://wxt.dev/">WXT</a>. It runs as a content script on the LinkBlitzer website and localhost dev URLs.</p>
<p><strong>What it does:</strong></p>
<ol>
<li>On load, announces itself: <code>window.postMessage({ type: &#39;LINKBLITZER:READY&#39; }, &#39;*&#39;)</code></li>
<li>Listens for <code>{ type: &#39;LINKBLITZER:OPEN&#39;, urls: string[] }</code> messages from the page</li>
<li>Validates <code>event.origin</code> against an allowlist (<code>https://linkblitzer.com</code>, <code>http://localhost:3000</code>, <code>http://localhost:5173</code>)</li>
<li>Opens each URL with <code>window.open(url, &#39;_blank&#39;)</code></li>
</ol>
<p><strong>Dev (side-load in browser):</strong></p>
<pre><code class="language-bash"># Chrome
npm run dev:ext:chrome     # from root
# or: npm run dev:chrome -w packages/extension

# Firefox
npm run dev:ext:firefox
# or: npm run dev:firefox -w packages/extension

# Safari
npm run dev:ext:safari
# or: npm run dev:safari -w packages/extension
</code></pre>
<p>WXT will build the extension and open a browser with it loaded automatically (Chrome/Firefox). For Safari, it generates an Xcode project.</p>
<p><strong>Build:</strong></p>
<pre><code class="language-bash">npm run build:ext             # Chrome (MV3)
npm run build:ext:firefox     # Firefox
npm run build:ext:safari      # Safari
</code></pre>
<p>Output is in <code>packages/extension/.output/</code>.</p>
<p><strong>Side-loading (manual install without publishing):</strong></p>
<ul>
<li><strong>Chrome/Edge:</strong> Go to <code>chrome://extensions</code>, enable &quot;Developer mode&quot;, click &quot;Load unpacked&quot;, and select <code>packages/extension/.output/chrome-mv3/</code></li>
<li><strong>Firefox:</strong> Go to <code>about:debugging#/runtime/this-firefox</code>, click &quot;Load Temporary Add-on&quot;, and select any file inside <code>packages/extension/.output/firefox-mv3/</code></li>
<li><strong>Safari:</strong> Build the Safari target (<code>npm run build:ext:safari</code>), open the generated Xcode project, and run it. Enable the extension in Safari&#39;s settings under Extensions</li>
</ul>
<p><strong>Publishing (TODO):</strong></p>
<ul>
<li><strong>Chrome Web Store:</strong> Create a developer account, zip the <code>chrome-mv3</code> output, and submit via the <a href="https://chrome.google.com/webstore/devconsole">Chrome Developer Dashboard</a>. Review typically takes a few days.</li>
<li><strong>Firefox Add-ons (AMO):</strong> Submit the <code>firefox-mv3</code> zip at <a href="https://addons.mozilla.org/developers/">addons.mozilla.org</a>. Firefox requires source code submission for review.</li>
<li><strong>Safari Extensions:</strong> Distribute through the Mac App Store. Requires an Apple Developer account and app review. The WXT Safari output is an Xcode project that wraps the extension in a native app container.</li>
<li><strong>Edge Add-ons:</strong> The Chrome MV3 build can typically be submitted as-is to the <a href="https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home">Microsoft Edge Add-ons</a> store.</li>
</ul>
<hr>
<h2>Root commands</h2>
<pre><code class="language-bash">npm run dev:website           # website dev server
npm run dev:ext:chrome        # extension dev (Chrome)
npm run dev:ext:firefox       # extension dev (Firefox)
npm run dev:ext:safari        # extension dev (Safari)

npm run build:core            # build core
npm run build:website         # build website
npm run build:ext             # build extension (Chrome)
npm run build:ext:firefox     # build extension (Firefox)
npm run build:ext:safari      # build extension (Safari)

npm test                      # run core tests
npm run lint                  # ESLint
npm run format                # Prettier
</code></pre>
<hr>
<h2>Tech stack</h2>
<ul>
<li>Vue 3 + TypeScript (Composition API, <code>&lt;script setup&gt;</code>)</li>
<li>Vue Router</li>
<li>Vite</li>
<li>WXT (browser extension framework)</li>
<li>Zod</li>
<li>Vitest</li>
<li>ESLint + Prettier</li>
<li>npm workspaces</li>
</ul>
`,
    url: "https://github.com/yaq1n0/LinkBlitzer",
    language: "Vue",
    topics: [],
    archived: false,
    createdAt: "2026-03-19T12:08:05Z",
    updatedAt: "2026-03-19T12:08:45Z"
  },
  {
    id: "LinkBlitzer-v1",
    name: "LinkBlitzer-v1",
    description: "WE GO BRR WITH THE LINKS",
    htmlDescription: `<h1>LinkBlitzer</h1>
<p>A simple, lightweight web utility that allows you to create a single URL that opens multiple URLs in separate tabs.
Perfect for daily workflows, research sessions, or sharing collections of links.</p>
<h2>Features</h2>
<ul>
<li><strong>Single Link, Multiple Tabs</strong>: Create one URL that opens many URLs</li>
<li><strong>Optimistic URL validation</strong>: URLs are optimistically validated as you type</li>
<li><strong>Copy to Clipboard</strong>: One-click copying of generated links</li>
<li><strong>Auto-redirect</strong>: Generated links automatically open URLs and redirect back</li>
<li><strong>Smart Popup Detection</strong>: Automatically detects and guides users through popup setup</li>
<li><strong>Browser-Specific Instructions</strong>: Tailored guidance for Chrome, Firefox, Safari, and Edge</li>
<li><strong>Dark Mode Support</strong>: Automatically follows your system&#39;s dark/light theme preference</li>
<li><strong>Minimal Design</strong>: Clean, fast-loading interface with smooth theme transitions</li>
<li><strong>No Dependencies</strong>: Pure HTML, CSS, and TypeScript (compiles to vanilla JS)</li>
</ul>
<h3>Local Development</h3>
<pre><code class="language-bash"># Install dependencies
npm install

# Start development server (serves TypeScript directly)
npm run dev

# Type check without building
npm run type-check

# Build for production (TypeScript → dist/)
npm run build

# Preview production build
npm run preview

# Format code with Prettier
npm run prettier
</code></pre>
<p>The development server at <code>http://localhost:3000</code> includes:</p>
<ul>
<li><strong>Hot module reloading</strong> for instant TypeScript updates</li>
<li><strong>Type checking</strong> in your editor with full IntelliSense</li>
<li><strong>Source maps</strong> for debugging TypeScript in browser dev tools</li>
<li><strong>All features working</strong> including popup detection</li>
</ul>
<h3>TypeScript Benefits</h3>
<ul>
<li><strong>Type Safety</strong>: Catch errors at compile time</li>
<li><strong>Better IDE Support</strong>: Auto-completion, refactoring, navigation</li>
<li><strong>Self-Documenting</strong>: Interfaces and types serve as documentation</li>
<li><strong>Modular Architecture</strong>: Clean separation of concerns</li>
<li><strong>Zero Runtime Cost</strong>: Compiles to optimized vanilla JavaScript</li>
</ul>
<h2>How It Works</h2>
<h3>Smart Popup Management</h3>
<p>LinkBlitzer automatically detects if popups are blocked and provides:</p>
<ul>
<li><strong>Visual status banners</strong>: Green &quot;READY TO BLITZ&quot; when popups work, red warning when blocked</li>
<li><strong>Browser-specific instructions</strong>: Tailored steps for your specific browser (Chrome, Firefox, Safari, Edge)</li>
<li><strong>One-click testing</strong>: Retest popup permissions after making changes</li>
<li><strong>Link generation control</strong>: Only allows creating links when popups are properly enabled</li>
</ul>
<h3>Automatic Dark Mode</h3>
<ul>
<li><strong>System integration</strong>: Automatically follows your device&#39;s dark/light mode setting</li>
<li><strong>Smooth transitions</strong>: Clean animations when switching between themes</li>
<li><strong>Optimized colors</strong>: Carefully selected dark mode palette that&#39;s easy on the eyes</li>
<li><strong>Consistent branding</strong>: Popup banners remain vibrant and readable in both themes</li>
</ul>
<h3>Creating Links</h3>
<ol>
<li>Visit <code>linkblitzer.com</code></li>
<li>The app will automatically test popup permissions</li>
<li>If popups are blocked, follow the browser-specific instructions shown</li>
<li>Enter URLs (one per line) in the text area</li>
<li>Copy the generated link when all URLs are valid</li>
<li>Share the link with anyone (they will also have to enable popups for things to work)</li>
</ol>
<h3>Opening Links</h3>
<ol>
<li>Visit a generated LinkBlitzer URL (make sure that popups are enabled)</li>
<li>All URLs will automatically open in new tabs</li>
<li>Page redirects back to clean URL for creating more links</li>
</ol>
<h2>Browser Support</h2>
<p>LinkBlitzer includes built-in support and guidance for:</p>
<ul>
<li><strong>Chrome/Chromium</strong>: Settings → Privacy and security → Site settings → Pop-ups and redirects</li>
<li><strong>Firefox</strong>: Settings → Privacy &amp; Security → Permissions → Pop-up windows exceptions</li>
<li><strong>Safari</strong>: Settings → Websites → Pop-up Windows → Allow for site</li>
<li><strong>Microsoft Edge</strong>: Settings → Cookies and site permissions → Pop-ups and redirects</li>
</ul>
<p>Each browser shows specific step-by-step instructions with links to official documentation.</p>
<h2>Usage Examples</h2>
<p><strong>Base URL (Create Mode):</strong></p>
<pre><code>https://{localhost:3000|linkblitzer.com}
</code></pre>
<p><strong>Generated LinkBlitzer URL:</strong></p>
<pre><code>https://{localhost:3000|linkblitzer.com}?urls=https%3A//example.com%7Chttps%3A//google.com%7Chttps%3A//github.com
</code></pre>
<h2>License</h2>
<p>MIT License - see <a href="https://github.com/yaq1n0/LinkBlitzer-v1/blob/main/LICENSE.md">LICENSE.md</a> for details.</p>
`,
    url: "https://github.com/yaq1n0/LinkBlitzer-v1",
    language: "TypeScript",
    topics: [],
    archived: false,
    createdAt: "2025-07-29T23:29:56Z",
    updatedAt: "2026-03-20T21:19:25Z"
  },
  {
    id: "opl-py",
    name: "opl-py",
    description: "Python OpenPowerlifting SDK | monorepo with web app, demo and pretrained models",
    htmlDescription: `<h1>opl-py</h1>
<p>A typed Python SDK for working with <a href="https://www.openpowerlifting.org/">OpenPowerlifting</a> data. Query lifters, meets, and rankings from a local DuckDB database built from the official OpenPowerlifting bulk CSV. Includes optional ML-based trajectory prediction analytics module.</p>
<h2>0a. PyPI Installation (for usage)</h2>
<p>To install opl-py from PyPI for usage:</p>
<pre><code class="language-bash">pip install opl-py
</code></pre>
<p>For optional analytics features (trajectory prediction, percentile rankings):</p>
<pre><code class="language-bash">pip install opl-py[analytics]
</code></pre>
<h2>0b. Local/Editable installation (for development):</h2>
<p>To install opl-py as an editable package, not from PyPI, use:</p>
<pre><code class="language-bash">make install
</code></pre>
<p>or directly with pip:</p>
<pre><code class="language-bash">pip install -e &quot;.[dev,analytics]&quot;
</code></pre>
<h2>1. Quick Start</h2>
<p>Download and ingest the full OPL dataset (~250 MB) into a local DuckDB file:
DuckDB path is <code>{platform_dirs.user_data_dir}/opl-py/opl.duckdb</code></p>
<pre><code class="language-bash">opl init
</code></pre>
<p>Update the database</p>
<pre><code class="language-bash">opl update
</code></pre>
<p>Then query it with the opl Python sdk.</p>
<pre><code class="language-python">import opl

client = opl.OPL()

# Look up a lifter
lifter = client.lifter(&quot;Ray Williams #1&quot;)
print(lifter.best_total_kg)
print(lifter.competition_count)

for entry in lifter.history():
    print(f&quot;{entry.date}: {entry.total_kg}kg @ {entry.bodyweight_kg}kg&quot;)

# Query rankings
top_raw = client.rankings(
    sex=opl.Sex.MALE,
    equipment=opl.Equipment.RAW,
    event=opl.Event.SBD,
    weight_class=&quot;93&quot;,
    order_by=&quot;dots&quot;,
    limit=10,
)

# Raw SQL for custom queries
results = client.query(
    &quot;SELECT Federation, COUNT(*) as n FROM entries GROUP BY Federation ORDER BY n DESC LIMIT 10&quot;
)
</code></pre>
<h2>Web App Development (with HMR)</h2>
<p>To run the API and UI locally with hot-reload:</p>
<pre><code class="language-bash">make dev
</code></pre>
<p>This starts both servers in parallel:</p>
<ul>
<li><strong>API</strong> — uvicorn on <code>http://localhost:8000</code> with <code>--reload</code> (restarts on Python file changes)</li>
<li><strong>UI</strong> — Vite dev server on <code>http://localhost:5173</code> with HMR (React fast refresh)</li>
</ul>
<h2>Additional Documentation</h2>
<table>
<thead>
<tr>
<th>Guide</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><a href="https://github.com/yaq1n0/opl-py/blob/main/docs/SDK.md">SDK</a></td>
<td>Python client, models, and enums</td>
</tr>
<tr>
<td><a href="https://github.com/yaq1n0/opl-py/blob/main/docs/ANALYTICS.md">Analytics</a></td>
<td>Percentile rankings, feature extraction, trajectory prediction</td>
</tr>
<tr>
<td><a href="https://github.com/yaq1n0/opl-py/blob/main/docs/DOCKER.md">Docker</a></td>
<td>Docker setup for the web app ui</td>
</tr>
</tbody></table>
<h2>Attribution</h2>
<p>This project uses data from the <a href="https://www.openpowerlifting.org/">OpenPowerlifting</a> project. OpenPowerlifting data is contribueted to the public domain.</p>
`,
    url: "https://github.com/yaq1n0/opl-py",
    language: "Python",
    topics: [],
    archived: false,
    createdAt: "2026-03-18T07:33:21Z",
    updatedAt: "2026-03-20T21:23:27Z"
  },
  {
    id: "prompt-as-endpoint",
    name: "prompt-as-endpoint",
    description: "npm package to simplify creating AI-powered APIs",
    htmlDescription: `<h1>prompt-as-endpoint</h1>
<p>Helper library for creating HTTP endpoints that use LLMs to return schema-validated JSON responses.</p>
<h2>Quick Start</h2>
<pre><code class="language-bash">npm install
npm run build
npm run demo:dev
</code></pre>
<p>Visit <code>http://localhost:3000</code> and try:</p>
<pre><code class="language-bash">curl -X POST http://localhost:3000/greet \\
  -H &quot;Content-Type: application/json&quot; \\
  -d &#39;{&quot;firstName&quot;:&quot;John&quot;,&quot;lastName&quot;:&quot;Doe&quot;}&#39;
</code></pre>
<h2>Packages</h2>
<ul>
<li><a href="https://github.com/yaq1n0/prompt-as-endpoint/blob/main/packages/prompt-as-endpoint"><code>prompt-as-endpoint</code></a> - Main library</li>
<li><a href="https://github.com/yaq1n0/prompt-as-endpoint/blob/main/packages/prompt-as-endpoint-demo"><code>prompt-as-endpoint-demo</code></a> - Demo server</li>
</ul>
<h2>License</h2>
<p>MIT</p>
`,
    url: "https://github.com/yaq1n0/prompt-as-endpoint",
    language: "TypeScript",
    topics: [],
    archived: false,
    createdAt: "2025-09-18T22:21:47Z",
    updatedAt: "2026-03-20T21:20:31Z"
  },
  {
    id: "pwordGen",
    name: "pwordGen",
    description: "Minimalist TypeScript password generation package",
    htmlDescription: `<h1>pwordgen</h1>
<p>A tiny, TypeScript-native password generator for browser and Node.js environments.</p>
<h2>Installation</h2>
<pre><code class="language-bash">npm install pwordgen
</code></pre>
<h2>Quick Start</h2>
<pre><code class="language-typescript">import { generatePassword, estimateEntropyBits } from &#39;pwordgen&#39;;

// Generate a password with defaults (16 chars, all character classes)
const password = generatePassword();

// Estimate entropy
const entropy = estimateEntropyBits({ length: 16 });
console.log(\`Entropy: \${entropy.toFixed(1)} bits\`);
</code></pre>
<h2>API</h2>
<h3><code>generatePassword(options?): string</code></h3>
<p>Generates a cryptographically secure password.</p>
<pre><code class="language-typescript">interface PasswordOptions {
  length: number; // Default: 16
  lowercase: boolean; // Default: true
  uppercase: boolean; // Default: true
  digits: boolean; // Default: true
  symbols: boolean; // Default: true
  custom: string; // Default: &#39;&#39;
  excludeSimilar: boolean; // Default: false (excludes il1Lo0O)
  exclude: string; // Default: &#39;&#39;
  requireEachSelectedClass: boolean; // Default: false
}
</code></pre>
<h4>Examples</h4>
<pre><code class="language-typescript">// Custom length
generatePassword({ length: 12 });

// Letters only
generatePassword({ digits: false, symbols: false });

// Exclude similar characters
generatePassword({ excludeSimilar: true });

// Custom character set
generatePassword({
  lowercase: false,
  uppercase: false,
  digits: false,
  symbols: false,
  custom: &#39;ABCDEF0123456789&#39;,
});

// Ensure at least one from each selected class
generatePassword({
  length: 12,
  requireEachSelectedClass: true,
});
</code></pre>
<h3><code>estimateEntropyBits(options?): number</code></h3>
<p>Calculates estimated entropy in bits for the given configuration.</p>
<pre><code class="language-typescript">const entropy = estimateEntropyBits({
  length: 12,
  digits: false,
  symbols: false,
});
</code></pre>
<h3>Character Classes</h3>
<pre><code class="language-typescript">import { CHARACTER_CLASSES } from &#39;pwordgen&#39;;

CHARACTER_CLASSES.lowercase; // &quot;abcdefghijklmnopqrstuvwxyz&quot;
CHARACTER_CLASSES.uppercase; // &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;
CHARACTER_CLASSES.digits; // &quot;0123456789&quot;
CHARACTER_CLASSES.symbols; // &quot;!@#$%^&amp;*()_+-=[]{}|;:,.&lt;&gt;?&quot;
CHARACTER_CLASSES.similar; // &quot;il1Lo0O&quot;
</code></pre>
<h2>Security</h2>
<ul>
<li>Uses Web Crypto API (browser) and Node.js crypto module</li>
<li>Rejection sampling ensures uniform distribution</li>
<li>No network calls or telemetry</li>
<li>Cryptographically secure random number generation</li>
</ul>
<h2>Browser Support</h2>
<p>Chrome 37+, Firefox 34+, Safari 7.1+, Edge 12+</p>
<h2>Node.js Support</h2>
<p>Node.js 16+</p>
<h2>Development</h2>
<pre><code class="language-bash">npm install          # Install dependencies
npm test             # Run tests
npm run build        # Build package
npm run lint         # Lint code
npm run prettier:fix # Format code
</code></pre>
<h2>License</h2>
<p>MIT</p>
`,
    url: "https://github.com/yaq1n0/pwordGen",
    language: "TypeScript",
    topics: [],
    archived: false,
    createdAt: "2025-08-30T22:00:43Z",
    updatedAt: "2026-03-20T21:18:15Z"
  },
  {
    id: "pwordGen.com",
    name: "pwordGen.com",
    description: "pwordGen.com website, uses pwordGen package",
    htmlDescription: `<h1>pwordgen.com Frontend</h1>
<p>A minimal, fast, client-side website that generates secure passwords using the <code>pwordgen</code> npm package.</p>
<h2>Features</h2>
<ul>
<li><strong>Secure Password Generation</strong>: Uses cryptographically strong randomness via the <code>pwordgen</code> package</li>
<li><strong>Client-Side Only</strong>: No data is sent to any server - everything runs in your browser</li>
<li><strong>Customizable Options</strong>: Control length, character types, exclusions, and requirements</li>
<li><strong>Entropy Display</strong>: Shows password strength in bits</li>
<li><strong>URL Persistence</strong>: Options are saved in URL parameters for easy sharing</li>
<li><strong>Responsive Design</strong>: Works on desktop and mobile devices</li>
<li><strong>Accessible</strong>: Keyboard navigation and screen reader friendly</li>
</ul>
<h2>Development</h2>
<h3>Prerequisites</h3>
<ul>
<li>Node.js 20+</li>
<li>npm</li>
</ul>
<h3>Setup</h3>
<pre><code class="language-bash">npm install
</code></pre>
<h3>Development Commands</h3>
<pre><code class="language-bash"># Start development server
npm run dev

# Run tests
npm run test

# Run tests in UI mode
npm run test:ui

# Type checking
npm run type-check

# Linting
npm run lint

# Code formatting
npm run prettier

# Build for production
npm run build

# Preview production build
npm run preview
</code></pre>
<h3>Tech Stack</h3>
<ul>
<li><strong>Vue 3</strong> - Progressive JavaScript framework</li>
<li><strong>TypeScript</strong> - Type safety and better developer experience</li>
<li><strong>Vite</strong> - Fast build tool and development server</li>
<li><strong>Vitest</strong> - Fast unit testing framework</li>
<li><strong>ESLint</strong> - Code linting</li>
<li><strong>Prettier</strong> - Code formatting</li>
</ul>
<h3>Testing</h3>
<p>The project includes comprehensive tests covering:</p>
<ul>
<li>Component rendering</li>
<li>User interactions</li>
<li>Password generation</li>
<li>Option persistence</li>
<li>Error handling</li>
<li>Copy functionality</li>
</ul>
<h3>Deployment</h3>
<p>This project uses a two-stage GitHub Actions CI/CD pipeline:</p>
<h4>1. CI Workflow (<code>.github/workflows/ci.yml</code>)</h4>
<p>Runs on every push and pull request to <code>main</code>:</p>
<ul>
<li>Type checking with TypeScript</li>
<li>Code linting with ESLint</li>
<li>Code formatting check with Prettier</li>
<li>Unit tests with Vitest</li>
</ul>
<h4>2. Publish Workflow (<code>.github/workflows/publish.yml</code>)</h4>
<p>Runs automatically after CI completes successfully on <code>main</code>:</p>
<ul>
<li>Builds the production bundle</li>
<li>Deploys to GitHub Pages</li>
</ul>
<p><strong>To deploy:</strong></p>
<ol>
<li>Push changes to <code>main</code> branch</li>
<li>CI workflow runs quality checks</li>
<li>If CI passes, publish workflow automatically deploys to GitHub Pages</li>
</ol>
<h3>Security</h3>
<ul>
<li>Uses Web Crypto API for secure random number generation</li>
<li>No external dependencies for password generation</li>
<li>No telemetry or analytics</li>
<li>No network requests during password generation</li>
<li>All processing happens client-side</li>
</ul>
<h2>License</h2>
<p>MIT</p>
`,
    url: "https://github.com/yaq1n0/pwordGen.com",
    language: "TypeScript",
    topics: [],
    archived: false,
    createdAt: "2025-08-30T22:24:22Z",
    updatedAt: "2026-03-20T21:18:27Z"
  },
  {
    id: "PythonTrayShortcuts",
    name: "PythonTrayShortcuts",
    description: "Windows tray script launcher, inspired TrayRunner",
    htmlDescription: `<h1>PythonTrayShortcuts</h1>
<p> Create your own custom tray launchpad with python scripts</p>
<h2>Setup (user)</h2>
<ul>
<li>install python 3.13 or later</li>
<li><code>pip install -r requirements.txt</code></li>
<li><code>python3 main.py</code></li>
<li>you can then add the above command to launch on boot etc.</li>
</ul>
<h2>Testing</h2>
<ul>
<li>test suffix &quot;_test&quot;</li>
<li><code>unittest</code> python builtin testing library</li>
</ul>
<h2>TODO:</h2>
<ul>
<li><p>proper testing integration with visual studio code</p>
</li>
<li><p>auto format code on save in vs code</p>
</li>
<li><p>code completions/intellsense in vs code</p>
</li>
<li><p>load UI configuration from json file {&quot;items&quot;, [&quot;key1&quot;, &quot;SEPERATOR&quot;, &quot;key2&quot;]}</p>
</li>
<li><p>subprocess execution (execute .py file from runner) and drag n drop scripts into <code>/scripts</code></p>
</li>
<li><p>launch on boot support (Windows, MacOS, Linux?). Potentially can make this work as an intrinsic script that does OS detection and executes commands</p>
</li>
<li><p>custom logo.png support (should be possible, default to defaultLogo.png in hidden folder)</p>
</li>
<li><p>support for launch with admin rights (Windows), elevated (sudo) permissions in Linux and potentially bypassing some MacOS limitations (might need to deal with some stupid Apple Mac API shit)</p>
</li>
<li><p>determine async behavior, do we FIFO?</p>
</li>
</ul>
`,
    url: "https://github.com/yaq1n0/PythonTrayShortcuts",
    language: "Python",
    topics: [],
    archived: false,
    createdAt: "2024-10-20T20:22:50Z",
    updatedAt: "2026-03-20T21:14:50Z"
  },
  {
    id: "RotationalDynamicsSimulator",
    name: "RotationalDynamicsSimulator",
    description: "Rotational dynamics simulation and visualization desktop app",
    htmlDescription: `<h1>Rotational Dynamics Py</h1>
<p>This was a group coursework from my Engineering Foundation Year at University of Southampton&#39;s Malaysia Campus. 
It was a software engineering group project where the goal was to create a python app using tkinter as an educational aide to a certain mechanics topic. </p>
<p>We chose to create a rotational dyamics (angular momentum and inertia) calculator and visualizer. 
I was the only one with any real programming experience, so 99% of the code here is mine, albeit a much younger and less skilled version of myself. </p>
<p>However, despite my lack of experience at the time, I saw the potential of repurposing the bulk of the GUI code for this app into a desktop app template that I can use in the future for rapic prototyping. 
This app was made in python2, which was already deprecated at the time, because of an outdated coursework spec. And I haven&#39;t felt the need to update it. 
If you want to run it, use python 2.7 and tkinter. It should work, though you might also have to fix some minor bugs before it runs, entropy is real. </p>
<h1>Desktop App Template</h1>
<p>The core desktop app functionality in this project was then turned into <a href="https://github.com/yaq1n0/DesktopAppTemplate">DesktopAppTemplate</a>. 
Which has python 3 support and will be carried over into the future :)</p>
<h1>How to get this ancient thing to work :p</h1>
<p>Tested on a Ubuntu 22 VM because I didn&#39;t want to have to install python 2 onto any of my physical machines. 
<br>As always, start with. 
<br><code>sudo apt-get update -y; sudo apt-get upgrade</code></p>
<h3>install python 2</h3>
<p><code>sudo apt-get install python2</code></p>
<h3>install python-tk (for python2)</h3>
<p><code>sudo apt-get install python-tk</code></p>
<h3>install pip for python 2</h3>
<p><code>wget https://bootstrap.pypa.io/pip/2.7/get-pip.py</code>
<code>python2 get-pip.py</code></p>
<h3>use pip to install pillow</h3>
<p><code>python2 -m pip install Pillow</code></p>
`,
    url: "https://github.com/yaq1n0/RotationalDynamicsSimulator",
    language: "Python",
    topics: [],
    archived: false,
    createdAt: "2020-03-31T11:47:37Z",
    updatedAt: "2026-03-20T21:04:30Z"
  },
  {
    id: "RunwayRedeclarationCalculator",
    name: "RunwayRedeclarationCalculator",
    description: "Runway redeclaration calculation desktop app",
    htmlDescription: `<h1>Software Engineering Group Project - Runway Reclaration</h1>
<p>A Java + JavaFX desktop app using MVC principles and AGILE software development practices. </p>
<p><img src="https://raw.githubusercontent.com/yaq1n0/RunwayRedeclarationCalculator/main/misc/pilot.PNG" alt=""></p>
`,
    url: "https://github.com/yaq1n0/RunwayRedeclarationCalculator",
    language: "Java",
    topics: [],
    archived: false,
    createdAt: "2024-01-10T04:28:59Z",
    updatedAt: "2026-03-20T20:55:57Z"
  },
  {
    id: "STQL",
    name: "STQL",
    description: "A Haskell interpreter for STQL, an SQL-inspired language designed for Turtle RDF file manipulation",
    htmlDescription: `<h1>PLC</h1>
<p>Programming Language Concepts Coursework</p>
<h2>How to run</h2>
<ol>
<li><code>ghc Stql.hs</code></li>
<li><code>./Stql prN.stql</code></li>
<li>wait patiently</li>
</ol>
<h3>Disclaimer</h3>
<p>If something went wrong and you&#39;ve run <code>cabal install...</code> multiple times, you should delete the <code>dist-newstyle</code> folder and the <code>.ghc.environment...</code> files that showed up as a result cause they, most likely, will be incorrect, and run the command again, once.</p>
`,
    url: "https://github.com/yaq1n0/STQL",
    language: "Haskell",
    topics: [],
    archived: false,
    createdAt: "2024-01-10T04:32:23Z",
    updatedAt: "2026-03-20T21:08:42Z"
  },
  {
    id: "TetrECS",
    name: "TetrECS",
    description: "JavaFX Tetris clone with networked highscores",
    htmlDescription: `<h1>TetrECS</h1>
<p>Tetris game project for Programming 2 (1st year) coursework </p>
<h1>Compile and Run</h1>
<p>Technically this can be run using just maven cli and javafx cli. But the easiest way is to compile and run is to open the project with intellij IDEA (IDE used for this project) and create a run configuration that does <code>maven clean install</code> and \`\`javafx:run\` for you. </p>
<p><img src="https://raw.githubusercontent.com/yaq1n0/TetrECS/main/example_intellij_config.jpg" alt="example_intellij_config.jpg"></p>
<h1>Issues</h1>
<p>The game was meant to connect to a server on the University of Southampton&#39;s internal network, which requires you to use the University&#39;s VPN to connect to. So when you try to launch the game, it will throw errors trying to connect and enable the multiplayer functionality. I might fork this repository and make a single player version of this game if I feel like it at some point but in theory, bypassing the multiplayer connection code should work.   </p>
`,
    url: "https://github.com/yaq1n0/TetrECS",
    language: "Java",
    topics: [],
    archived: false,
    createdAt: "2024-02-13T13:35:46Z",
    updatedAt: "2026-03-20T20:59:45Z"
  },
  {
    id: "ThymPi",
    name: "ThymPi",
    description: "Final Year Project: Proof-of-concept for using sensor data to augment visual autonomous navigation systems",
    htmlDescription: `<h1>Setup Guide:</h1>
<p>This setup guide isn&#39;t step by step but instead a rough guide to help you get started 
as a lot of the installation process is highly dependent on the platform you intend to run this on. </p>
<p><strong>For reference, this is the development environment I used</strong>
<br>Computer: Raspberry Pi 3B+ 
<br>Operating System: Raspberry Pi OS (legacy) 
<br><em>note: this is the debian 10 (buster) based version</em></p>
<p><strong>MPU6050 Setup</strong> 
<br>The installation process for this is very simple, simply follow the instructions in the repository
<br>Repository: <a href="https://github.com/m-rtijn/mpu6050">https://github.com/m-rtijn/mpu6050</a></p>
<p><strong>Pi Camera Setup</strong>
<br>In order to setup and enable the Pi Camera interface, follow the instructions at the link below
<br>Pi Camera Documentation: <a href="https://picamera.readthedocs.io/en/release-1.13/install.html">https://picamera.readthedocs.io/en/release-1.13/install.html</a></p>
<p><strong>Thymio Interface Setup</strong>
<br>The installation process for this is very well explained in the repository below
<br>GitHub repository: <a href="https://github.com/lebalz/thympi">https://github.com/lebalz/thympi</a></p>
<p><strong>OpenCV Setup</strong>
<br>The OpenCV install process is very complicated and I suggest you look up the installation process
for your own system.
<br>However, the following article and forum is a good place to get started 
<br>Core Electronics: <a href="https://core-electronics.com.au/guides/object-identify-raspberry-pi/">https://core-electronics.com.au/guides/object-identify-raspberry-pi/</a></p>
`,
    url: "https://github.com/yaq1n0/ThymPi",
    language: "Python",
    topics: [],
    archived: false,
    createdAt: "2023-03-28T18:57:56Z",
    updatedAt: "2026-03-20T21:16:14Z"
  },
  {
    id: "TranslateApp",
    name: "TranslateApp",
    description: "Desktop translation/conversion app with Google Translate API integration, built with DesktopAppTemplate",
    htmlDescription: `<h1>Python text converter app</h1>
<p>The app was initally meant as a desktop app that would convert strings based on programmed rulesets (eg. randomcase). 
I think it&#39;s currently programmed with UwU-case. </p>
<h2>google translate API integration</h2>
<p>I then linked the app with google translate&#39;s API to get it to speak. 
I deeply regret this decision. </p>
<h1>DEVELOPMENT STATUS</h1>
<p>The app was made using an outdated version of <a href="https://github.com/yaq1n0/DesktopAppTemplate">DesktopAppTemplate</a>. 
Which means this thing probably still runs on Python 2.7, and the libraries I used and the API has probably stopped working. 
I might revisit this at some point to bring it back to life. </p>
`,
    url: "https://github.com/yaq1n0/TranslateApp",
    language: "Python",
    topics: [],
    archived: false,
    createdAt: "2020-06-01T15:29:27Z",
    updatedAt: "2026-03-20T21:03:35Z"
  },
  {
    id: "TrayRunner",
    name: "TrayRunner",
    description: "Spotlight-inspired macOS native script launcher",
    htmlDescription: `<h1>TrayRunner</h1>
<p>TrayRunner is a macOS menu bar application that allows you to quickly access and run scripts from your computer. The app sits in your menu bar and provides a fast, keyboard-accessible way to search and execute scripts.</p>
<h2>Features</h2>
<ul>
<li><strong>Global Keyboard Shortcut</strong>: Quickly open the script search HUD with ⌘+Shift+Space</li>
<li><strong>Script Directory Monitoring</strong>: Add script folders that automatically update when changes are detected</li>
<li><strong>TODO: Fuzzy Search</strong>: Type to quickly find and run the script you need</li>
<li><strong>Support for Multiple Script Types</strong>: Works with shell (.sh), Python (.py), Ruby (.rb), Perl (.pl), and PHP (.php) scripts // I only tested with .sh so far, might change in the future.</li>
</ul>
<h2>Requirements</h2>
<ul>
<li>macOS 15.0 or later // might work with older, I used 15, I don&#39;t plan on supporting older</li>
<li>Xcode 16.0 or later // might work with older, I used 16 tho</li>
</ul>
<h2>Installation</h2>
<h3>Option 1: Download the Release</h3>
<ol>
<li>Go to the <a href="https://github.com/yourusername/TrayRunner/releases">Releases</a> page</li>
<li>Download the latest version of TrayRunner.app.zip</li>
<li>Extract the ZIP file</li>
<li>Move TrayRunner.app to your Applications folder</li>
<li>Launch the app</li>
</ol>
<h3>Build from Source</h3>
<p>Just clone the project and Cmd + R in XCode</p>
<h2>Usage</h2>
<ol>
<li>After launching TrayRunner, you&#39;ll see a terminal icon in your menu bar</li>
<li>Click on the menu bar icon to open the menu and access settings</li>
<li>Press ⌘+Shift+Space to open the script search overlay</li>
<li>Add script folders by opening Settings → Watched Folders</li>
<li>Start typing to search for scripts, then press Enter to run the selected script</li>
</ol>
<h2>Development</h2>
<h3>Prerequisites</h3>
<ul>
<li>Xcode 13.0 or later</li>
<li>Swift 5.5 or later</li>
</ul>
<h3>Project Structure</h3>
<ul>
<li><code>TrayRunner/</code> - Main source code directory<ul>
<li><code>Data/</code> - Data models and script management</li>
<li><code>UI/</code> - User interface components<ul>
<li><code>Components/</code> - Reusable UI components</li>
<li><code>Settings/</code> - Settings interface</li>
<li><code>Search/</code> - Script search functionality</li>
</ul>
</li>
<li><code>Assets.xcassets/</code> - App assets and icons</li>
</ul>
</li>
</ul>
<h3>Dependencies</h3>
<ul>
<li><a href="https://github.com/sindresorhus/KeyboardShortcuts">KeyboardShortcuts</a> - For global keyboard shortcut handling</li>
</ul>
<h2>Contributing</h2>
<p>Contributions are welcome! If you&#39;d like to contribute:</p>
<ol>
<li>Fork repo</li>
<li>Make PR</li>
</ol>
<h2>License</h2>
<p>This project is licensed under the MIT License - see the LICENSE file for details.</p>
`,
    url: "https://github.com/yaq1n0/TrayRunner",
    language: "Swift",
    topics: [],
    archived: false,
    createdAt: "2025-04-27T02:22:05Z",
    updatedAt: "2026-03-20T21:16:42Z"
  },
  {
    id: "VidSrcWrapper",
    name: "VidSrcWrapper",
    description: "Self-hostable web app for watching movies & shows easily by searching for them on TMDB and watching them with VidSrc",
    htmlDescription: `<h1>VidSrc Wrapper - TMDB Movie Search</h1>
<p>A TypeScript movie search application using The Movie Database (TMDB) API, which also happens hook into VidSrc.. and in theory any other <em>legal</em> streaming service that uses IMDB/TMDB ids.</p>
<p>This isn&#39;t hosted anywhere, but it&#39;s made in such a way to make it very simple to run on your own servers.</p>
<p><strong>Stack:</strong> Full-stack Typescript, Vue 3 + Vite client, Hono server</p>
<h2>Setup</h2>
<p><strong>Prerequisites:</strong> TMDB Read Access Token (Bearer auth) (<a href="https://www.themoviedb.org/settings/api">get one here</a>)</p>
<ol>
<li><p><strong>Install dependencies:</strong></p>
<pre><code class="language-bash">npm install
</code></pre>
</li>
<li><p><strong>Create <code>.env</code> file in root:</strong></p>
<pre><code class="language-env">TMDB_API_KEY=your_tmdb_read_access_token_here
</code></pre>
</li>
<li><p><strong>Run</strong></p>
<pre><code class="language-bash">npm run dev
</code></pre>
</li>
</ol>
<p>This starts:</p>
<ul>
<li>Backend at <code>http://localhost:8080</code></li>
<li>Frontend at <code>http://localhost:3000</code></li>
</ul>
`,
    url: "https://github.com/yaq1n0/VidSrcWrapper",
    language: "TypeScript",
    topics: [],
    archived: false,
    createdAt: "2025-08-10T02:17:15Z",
    updatedAt: "2026-03-20T21:22:37Z"
  },
  {
    id: "voidapply.com",
    name: "voidapply.com",
    description: "Apply for jobs faster than everyone else, straight to the void!",
    htmlDescription: `<h1>VoidApply</h1>
<p><strong>Apply faster than ever. Right to the void.</strong></p>
<p>A satirical job board with parody ATS interfaces that lets you fill out an application and rejects you immediately. Built as catharsis for everyone who&#39;s applied to 200 jobs and heard back from 0.</p>
<hr>
<h2>What it does</h2>
<ol>
<li>Search for a job</li>
<li>Fill out a full application</li>
<li>Get rejected, instantly</li>
</ol>
<hr>
<h2>Tech</h2>
<ul>
<li>Vite + React 18 + TypeScript</li>
<li>React Router v6 — URL is the source of truth</li>
<li>Tailwind CSS v3 + Framer Motion</li>
<li>Fuse.js for client-side fuzzy search</li>
<li>No backend. No APIs. Pure static SPA.</li>
<li>Deployed with Cloudflare Pages</li>
</ul>
<hr>
<h2>ATS Skins</h2>
<p>Parody clones of real applicant tracking systems:</p>
<ul>
<li><strong>WorkNight</strong> — Workday. Eight steps to submit a CV you already uploaded.</li>
<li><strong>GreenHouse of Pain</strong> — Greenhouse. AI screening badge, passion scale, instant regret.</li>
<li><strong>Talaeo</strong> — Taleo/Oracle. Early-2010s enterprise UI. Session timeout. Misaligned fields.</li>
</ul>
<h2>Rejection Modes</h2>
<ul>
<li><strong>Dev Null</strong> — <code>cat application.pdf | /dev/null</code></li>
<li><strong>Ghost</strong> — Spinner, then silence. Forever.</li>
<li><strong>Speedrun</strong> — REJECTED in 0.003 seconds. World record: Amazon, 0.002s.</li>
<li><strong>Fake Email</strong> — A personalized rejection from HR. Your CV will be kept on file. 4...3...2...1. Deleted.</li>
</ul>
<hr>
<h2>Development | Quick Start Guide</h2>
<pre><code class="language-bash">npm install
npm run dev
</code></pre>
<pre><code class="language-bash">npm run build   # production build
npm run test    # vitest
</code></pre>
<h2>Debugging</h2>
<p>You should be able to find everything you need for debugging the ATS skins and Rejection modes at <code>/debug</code></p>
`,
    url: "https://github.com/yaq1n0/voidapply.com",
    language: "TypeScript",
    topics: [],
    archived: false,
    createdAt: "2026-03-13T04:22:15Z",
    updatedAt: "2026-03-20T21:23:14Z"
  },
  {
    id: "yaq1n0",
    name: "yaq1n0",
    description: "Profile README",
    htmlDescription: `<h1>Yaqin - <em>computer dude</em></h1>
<p>I&#39;m a full-stack software engineer that builds somewhat cool stuff that I would actually want to use. </p>
<p>Forever spending 5 days automating things I could do in 5 minutes. </p>
<p>My last words will be &quot;That&#39;s not even that complex, I could totally build that myself, how hard could it be?&quot;</p>
<p>Dabbling in compilers, systems programming, hardware/embedded stuff. </p>
<h2>Other things I am known for</h2>
<ul>
<li>Shoving inordinate amounts of <a href="https://uk.pcpartpicker.com/b/XyH2FT">overclocked hardware into shoeboxes</a> and trying to not start a fire. </li>
<li>Lifting <a href="https://www.openpowerlifting.org/u/yaqinhasan">moderately heavy objects</a> for internet points. </li>
<li>Setting up <em>production grade</em> servers and homelab projects even though I&#39;m the only user.</li>
</ul>
`,
    url: "https://github.com/yaq1n0/yaq1n0",
    language: null,
    topics: [],
    archived: false,
    createdAt: "2026-02-23T07:42:18Z",
    updatedAt: "2026-03-20T19:44:16Z"
  },
  {
    id: "yaqinhasan.com",
    name: "yaqinhasan.com",
    description: "Yet another dev portfolio site. ",
    htmlDescription: `<h1>yaqinhasan.com</h1>
<blockquote>
<p>Personal portfolio website built with Vue 3 &amp; TypeScript</p>
</blockquote>
<h2>Quick Start</h2>
<h3>Cloning &amp; npm install</h3>
<pre><code class="language-bash">git clone https://github.com/yaq1n0/yaqinhasan.com.git
cd yaqinhasan.com
npm ci
</code></pre>
<h3>Package.json scripts</h3>
<pre><code class="language-bash"># Build
npm run build

# Run dev server
npm run dev

# Testing
npm run test
npm run test:watch
npm run test:coverage

# Code quality
npm run lint
npm run lint:fix

# Formatting
npm run prettier
npm run prettier:fix
</code></pre>
<h2>Feature breakdown</h2>
<h3>JSON -&gt; Web CV</h3>
<ul>
<li>Displays cv.json dynamically using Vue.</li>
<li>Allows generation of cv.pdf using <code>render-pdf.ts</code>. (requires playwright setup with <code>npm run setup:playwright</code>)</li>
</ul>
<h3>Interactive &quot;Terminal&quot;</h3>
<ul>
<li>Allows users to interact with the website via a &quot;terminal&quot; interface</li>
<li>Allows power-users to configure things like dev-mode and themes</li>
<li>Unix commands for navigating the site</li>
<li>Is quite fun (supposedly)</li>
</ul>
<h3>Theme System</h3>
<ul>
<li>Users can pick from various themes</li>
<li>Themes come from <code>ThemeRegistry.ts</code></li>
<li>Themes have light and dark modes</li>
<li>Theme preference is stored in localStorage</li>
<li>Default theme light|dark mode detected from system prefers-dark</li>
</ul>
<h2>CI/CD</h2>
<p>There is a barebones CI pipeline in <code>ci.yaml</code> which does</p>
<ul>
<li>Unit testing</li>
<li>Validation of themes, including WCAG compliance</li>
<li>Linting</li>
<li>Formatting</li>
</ul>
<p>The build process generates a <code>dist/</code> folder with:</p>
<ul>
<li>Static HTML files for each route</li>
<li>Optimized JavaScript and CSS bundles</li>
<li>All public assets with proper paths</li>
<li>404.html for fallback handling</li>
</ul>
<p>Currently deployed to Github Pages using <code>deploy.yml</code></p>
<h2>Links</h2>
<ul>
<li><strong>Live Site</strong>: <a href="https://yaqinhasan.com">yaqinhasan.com</a></li>
<li><strong>GitHub</strong>: <a href="https://github.com/yaq1n0/yaqinhasan.com">github.com/yaq1n0/yaqinhasan.com</a></li>
<li><strong>LinkedIn</strong>: <a href="https://linkedin.com/in/yaqinhasan">linkedin.com/in/yaqinhasan</a></li>
</ul>
`,
    url: "https://github.com/yaq1n0/yaqinhasan.com",
    language: "Vue",
    topics: [],
    archived: false,
    createdAt: "2025-01-14T00:04:55Z",
    updatedAt: "2026-03-20T21:23:53Z"
  },
  {
    id: "yaqinhasan.com-v1",
    name: "yaqinhasan.com-v1",
    description: "yaqinhasan.com - first implementation",
    htmlDescription: `<h1>yaqinhasan.com - first implementation using templates and first minimalist (from scratch) implementations.</h1>
<p>this is where the source code for the abandoned monica template version and the alpha versions of the minimalist approach will be kept for posterity. </p>
<p>Welcome to the source code of yaqinhasan.com</p>
<p>The rest of this readme file is just notes for where I can get the resources used in the site. 
The .svg Icons of other companies are from <a href="https://icons.getbootstrap.com">https://icons.getbootstrap.com</a>, this is mainly used for the contact box in contact.html and index.html. </p>
<p>The favicon was made with a favicon generator using an svg generated from <a href="https://danmarshall.github.io/google-font-to-svg-path/">https://danmarshall.github.io/google-font-to-svg-path/</a></p>
<p>The font used globally is JetBrains Mono, obtainable from <a href="https://www.jetbrains.com/lp/mono/">https://www.jetbrains.com/lp/mono/</a> or through google&#39;s font API <a href="https://fonts.google.com/specimen/JetBrains+Mono">https://fonts.google.com/specimen/JetBrains+Mono</a></p>
`,
    url: "https://github.com/yaq1n0/yaqinhasan.com-v1",
    language: "HTML",
    topics: [],
    archived: false,
    createdAt: "2024-02-06T17:56:44Z",
    updatedAt: "2026-03-20T21:06:25Z"
  },
  {
    id: "yaqinhasan.com-v2",
    name: "yaqinhasan.com-v2",
    description: "yaqinhasan.com - final pure html, css and javascript version",
    htmlDescription: `<h1>Welcome to the source code of <code>yaqinhasan.com</code></h1>
<p>This is the current repository for the source code for <code>yaqinhasan.com</code>
The previous repository containing abandoned approaches and alpha versions has been made private and deprecated to avoid confusion. </p>
<h1>CSS Tree</h1>
<p>Most sites have one gigantic <code>styles.css</code> file, I didn&#39;t want to do this because, while this does improve site performance by reducing <code>HTTP GET</code> requests, this makes the development process much more tedious. </p>
<p>Having the css split into global and page files means that you can change the css for global components (found on one or more pages) and page components (found in a certain html page) separately. </p>
<p>Additionally, having separate files means that each file is actually manageable and reduces the amount of code repetition, incentivizing shorter class names, increased used of polymorphism and code modularity. </p>
<p>Lastly, once the site is done (or in a release stable state), there is a chance of me integrating some pre-deployment processing, using <code>CS</code> and <code>JavaScript</code> aggregators to make a single <code>styles.css</code> and <code>main.js</code> for deployment. </p>
<h1>JavaScript documentation (because I will definitely forget)</h1>
<h3>How the site handles cross-page shortcuts</h3>
<p>So a common user flow is to go from one page to specific point in another, this becomes a problem because the site has a lot of collapsible elements that are closed by default. 
So there needs to be a way for the one page to communicate to the other that the specific element it is redirecting to needs to be opened when the user gets there. 
Ideally, this would also only happen when the user uses this link, and not in any other cases. (no permanence)</p>
<p>How this is implemented: </p>
<p>functions within <code>shortcutsHandler.js</code>: </p>
<ul>
<li><p><code>gotoElement(&lt;element_id&gt;)</code> is for local shortcuts (same page), where the collapsible being linked to is opened and scrolled to. </p>
</li>
<li><p><code>openPageElement(&lt;page_name&gt;, &lt;element_id&gt;)</code> is for the source page to call.</p>
</li>
</ul>
<p><br>For example <code>pageA.html</code> will call <code>openPageElement(&#39;pageB&#39;, &#39;element0&#39;)</code> and a sessionStorage item will be created to store the information that <code>pageB_element0_opened</code> should be <code>true</code>. </p>
<ul>
<li><code>handleShortcuts(&lt;page_name&gt;)</code> is for the destination page to call (or more accurately, be bound to onload).</li>
</ul>
<p><br> For example <code>pageB.html</code> will have a file called <code>pageB.js</code> which has a function <code>pageBShortcuts()</code> that calls <code>handleShortcuts(&#39;pageB&#39;)</code>.
<br><code>handleShortcuts(&lt;page_name&gt;)</code> will then go iterate through session storage and try to match the <code>page_name</code> with an <code>_opened</code> item in sessionStorage. 
<br>Then it will extract the element_id from it and try to open the corresponding element. 
It should then finish off by deleting the sessionStorage item. </p>
<h3>The rest of this readme file is just notes for where I can get the resources used in the site.</h3>
<ul>
<li><p>The .svg Icons of other companies are from <a href="https://icons.getbootstrap.com">https://icons.getbootstrap.com</a>, this is mainly used for the contact box in contact.html and index.html. </p>
</li>
<li><p>The favicon was made with a favicon generator using an svg generated from <a href="https://danmarshall.github.io/google-font-to-svg-path/">https://danmarshall.github.io/google-font-to-svg-path/</a></p>
</li>
<li><p>The font used globally is JetBrains Mono, obtainable from <a href="https://www.jetbrains.com/lp/mono/">https://www.jetbrains.com/lp/mono/</a> or through google&#39;s font API <a href="https://fonts.google.com/specimen/JetBrains+Mono">https://fonts.google.com/specimen/JetBrains+Mono</a></p>
</li>
</ul>
`,
    url: "https://github.com/yaq1n0/yaqinhasan.com-v2",
    language: "HTML",
    topics: [],
    archived: false,
    createdAt: "2024-02-23T17:44:42Z",
    updatedAt: "2026-03-20T21:08:12Z"
  }
];
