import { readFileSync, readdirSync, writeFileSync, mkdirSync, copyFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import matter from "gray-matter";
import { Marked } from "marked";
import { createHighlighter } from "shiki";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BLOG_DIR = resolve(__dirname, "../content/blog");
const PUBLIC_DIR = resolve(__dirname, "../public");
const OUTPUT_PATH = resolve(__dirname, "../src/data/blog/blogPosts.ts");

const includeDrafts = process.argv.includes("--include-drafts");

/** Escape a string for use inside a JS template literal */
const escapeTemplateLiteral = (str: string): string => {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
};

async function main() {
  // Set up shiki highlighter
  const highlighter = await createHighlighter({
    themes: ["github-dark", "github-light"],
    langs: ["typescript", "javascript", "python", "bash", "json", "html", "css", "yaml", "markdown", "vue", "go", "rust", "sql"]
  });

  // Configure marked with shiki
  const marked = new Marked({
    renderer: {
      code({ text, lang }) {
        const language = lang || "text";
        try {
          return highlighter.codeToHtml(text, {
            lang: language,
            themes: { light: "github-light", dark: "github-dark" },
            defaultColor: false
          });
        } catch {
          // Fall back to plain code block for unsupported languages
          return `<pre><code class="language-${language}">${text}</code></pre>`;
        }
      }
    }
  });

  // Scan for post directories (each directory = one post, slug = directory name)
  const entries = readdirSync(BLOG_DIR, { withFileTypes: true });
  const dirs = entries.filter((e) => e.isDirectory());

  if (dirs.length === 0) {
    console.warn("No blog posts found in content/blog/");
  }

  const posts: Array<{
    slug: string;
    title: string;
    date: string;
    description: string;
    tags: string[];
    coverImage?: string;
    draft: boolean;
    content: string;
    htmlContent: string;
    readingTime: number;
  }> = [];

  for (const dir of dirs) {
    const slug = dir.name;
    const postDir = resolve(BLOG_DIR, slug);
    const mdPath = resolve(postDir, `${slug}.md`);
    const raw = readFileSync(mdPath, "utf-8");
    const { data: frontmatter, content } = matter(raw);

    // Validate frontmatter
    const { title, date, description, tags, coverImage, draft } = frontmatter as {
      title: string;
      date: string;
      description: string;
      tags: string[];
      coverImage?: string;
      draft?: boolean;
    };

    if (!title || !date || !description || !tags) {
      console.error(`Invalid frontmatter in ${slug}/${slug}.md: missing required fields (title, date, description, tags)`);
      process.exit(1);
    }

    const isDraft = draft ?? false;

    // Skip drafts unless flag is set
    if (isDraft && !includeDrafts) {
      console.log(`Skipping draft: ${slug}`);
      continue;
    }

    // Copy all non-md assets to public/blog-assets/[slug]/
    const assetFiles = readdirSync(postDir).filter((f) => !f.endsWith(".md"));
    if (assetFiles.length > 0) {
      const destDir = resolve(PUBLIC_DIR, "blog-assets", slug);
      mkdirSync(destDir, { recursive: true });
      for (const asset of assetFiles) {
        copyFileSync(resolve(postDir, asset), resolve(destDir, asset));
      }
    }

    // Rewrite ./relative-path image references to absolute public paths
    const rewrittenContent = content.replace(
      /!\[([^\]]*)\]\(\.\/([^)]+)\)/g,
      (_, alt, filename) => `![${alt}](/blog-assets/${slug}/${filename})`
    );

    const htmlContent = await marked.parse(rewrittenContent);
    const wordCount = content
      .replace(/[#*`\->\[\]()]/g, "")
      .split(/\s+/)
      .filter(Boolean).length;
    const readingTime = Math.max(1, Math.ceil(wordCount / 200));

    posts.push({
      slug,
      title,
      date,
      description,
      tags,
      coverImage,
      draft: isDraft,
      content,
      htmlContent,
      readingTime
    });
  }

  // Sort by date descending
  posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  // Collect all unique tags
  const allTags = [...new Set(posts.flatMap((p) => p.tags))].sort();

  // Generate output
  const output = `// AUTO-GENERATED by scripts/build-blog.ts — do not edit manually
import type { BlogPost } from "@/data/models/BlogPost";

export const blogPosts: BlogPost[] = [
${posts
  .map(
    (p) => `  {
    slug: ${JSON.stringify(p.slug)},
    title: ${JSON.stringify(p.title)},
    date: ${JSON.stringify(p.date)},
    description: ${JSON.stringify(p.description)},
    tags: ${JSON.stringify(p.tags)},
    coverImage: ${p.coverImage ? JSON.stringify(p.coverImage) : "undefined"},
    draft: ${p.draft},
    content: \`${escapeTemplateLiteral(p.content)}\`,
    htmlContent: \`${escapeTemplateLiteral(p.htmlContent)}\`,
    readingTime: ${p.readingTime}
  }`
  )
  .join(",\n")}
];

export const allTags: string[] = ${JSON.stringify(allTags)};

export const blogPostsBySlug: Record<string, BlogPost> = Object.fromEntries(blogPosts.map((p) => [p.slug, p]));
`;

  writeFileSync(OUTPUT_PATH, output, "utf-8");
  console.log(`Generated ${posts.length} blog post(s) → ${OUTPUT_PATH}`);
  console.log(`Tags: ${allTags.join(", ")}`);

  highlighter.dispose();
}

main().catch((err) => {
  console.error("Blog build failed:", err);
  process.exit(1);
});
