import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { marked } from "marked";
import type { components } from "@octokit/openapi-types";

/** octokit provided GitHub types */
type GitHubRepo = components["schemas"]["repository"];
type GitHubReadmeResponse = components["schemas"]["content-file"];

const __dirname = dirname(fileURLToPath(import.meta.url));
const GITHUB_USER = "yaq1n0"; // my GitHub username
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const authHeaders: Record<string, string> = GITHUB_TOKEN ? { Authorization: `Bearer ${GITHUB_TOKEN}` } : {};
const OUTPUT_PATH = resolve(__dirname, "../src/data/projects/githubProjects.ts"); // path to githubProjects.ts output file
const getBaseRawUrl = (repoName: string) => `https://raw.githubusercontent.com/${GITHUB_USER}/${repoName}/main/`;
const getBaseBlobUrl = (repoName: string) => `https://github.com/${GITHUB_USER}/${repoName}/blob/main/`;
const getReadmeUrl = (repoName: string) => `https://api.github.com/repos/${GITHUB_USER}/${repoName}/readme`;

/** Rewrite relative URLs in HTML to absolute GitHub URLs */
const rewriteRelativeUrls = (html: string, repoName: string): string => {
  const baseRaw = getBaseRawUrl(repoName);
  const baseBlob = getBaseBlobUrl(repoName);

  // Rewrite src attributes (images, videos) → raw.githubusercontent.com for direct file access
  html = html.replace(
    /(<(?:img|video|source)[^>]*\s(?:src)=["'])(?!https?:\/\/|#)(?:\.\/)?([^"']+)(["'])/gi,
    (_, prefix, path, suffix) => `${prefix}${baseRaw}${path}${suffix}`
  );

  // Rewrite href attributes on anchors → github.com/blob for browsable links
  html = html.replace(
    /(<a[^>]*\s(?:href)=["'])(?!https?:\/\/|#|mailto:)(?:\.\/)?([^"']+)(["'])/gi,
    (_, prefix, path, suffix) => `${prefix}${baseBlob}${path}${suffix}`
  );

  return html;
};

/** Fetch README for a repo, return HTML or null if no README */
const fetchReadmeHtml = async (repoName: string) => {
  const url = getReadmeUrl(repoName);
  const res = await fetch(url, {
    headers: { Accept: "application/vnd.github.v3+json", ...authHeaders }
  });

  if (res.status === 404) return undefined;
  if (!res.ok) {
    console.warn(`Failed to fetch README for ${repoName}: ${res.status}`);
    return undefined;
  }

  const data = (await res.json()) as GitHubReadmeResponse;
  const markdown = Buffer.from(data.content, "base64").toString("utf-8");
  const html = await marked(markdown);
  const withRewrittenUrls = rewriteRelativeUrls(html, repoName);
  return withRewrittenUrls;
};

/** Escape backticks and backslashes for safe embedding in a JS template literal */
const escapeForTemplateLiteral = (str: string): string => str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

async function main() {
  console.log(`Fetching repos for ${GITHUB_USER}...`);

  const reposRes = await fetch(`https://api.github.com/users/${GITHUB_USER}/repos?per_page=100`, {
    headers: { Accept: "application/vnd.github.v3+json", ...authHeaders }
  });

  if (!reposRes.ok) {
    console.error(`Failed to fetch repos: ${reposRes.status}`);
    process.exit(1);
  }

  const allRepos = (await reposRes.json()) as GitHubRepo[];
  const repos = allRepos.filter((r) => !r.fork);

  console.log(`Found ${repos.length} non-fork public repos. Fetching READMEs...`);

  const results = await Promise.all(
    repos.map(async (repo) => {
      console.log(`  ${repo.name}...`);
      return { repo, readmeHtml: await fetchReadmeHtml(repo.name) };
    })
  );

  const projects = results.map(({ repo, readmeHtml }) => `  {
    id: ${JSON.stringify(repo.name)},
    name: ${JSON.stringify(repo.name)},
    description: ${JSON.stringify(repo.description)},
    htmlDescription: ${readmeHtml ? `\`${escapeForTemplateLiteral(readmeHtml)}\`` : "null"},
    url: ${JSON.stringify(repo.html_url)},
    language: ${JSON.stringify(repo.language)},
    topics: ${JSON.stringify(repo.topics)},
    archived: ${repo.archived},
    createdAt: ${JSON.stringify(repo.created_at)},
    updatedAt: ${JSON.stringify(repo.updated_at)}
  }`);

  const output = `// AUTO-GENERATED by scripts/sync-github-projects.ts — do not edit manually
// Last synced: ${new Date().toISOString()}
import type { GitHubProject } from "@/data/models/Project";

export const githubProjects: GitHubProject[] = [
${projects.join(",\n")}
];
`;

  writeFileSync(OUTPUT_PATH, output);
  console.log(`\nWrote ${repos.length} projects to ${OUTPUT_PATH}`);
}

main();
