import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { marked } from "marked";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GITHUB_USER = "yaq1n0";
const OUTPUT_PATH = resolve(__dirname, "../src/data/projects/githubProjects.ts");

interface GitHubRepo {
  name: string;
  description: string | null;
  html_url: string;
  language: string | null;
  topics: string[];
  fork: boolean;
  archived: boolean;
  created_at: string;
  updated_at: string;
}

interface GitHubReadmeResponse {
  content: string; // base64-encoded
  encoding: string;
}

/** Rewrite relative URLs in HTML to absolute GitHub URLs */
function rewriteRelativeUrls(html: string, repoName: string): string {
  const baseRaw = `https://raw.githubusercontent.com/${GITHUB_USER}/${repoName}/main/`;
  const baseBlob = `https://github.com/${GITHUB_USER}/${repoName}/blob/main/`;

  // Rewrite src attributes (images, videos) → raw.githubusercontent.com for direct file access
  html = html.replace(
    /(<(?:img|video|source)[^>]*\s(?:src)=["'])(?!https?:\/\/|#)(?:\.\/)?([^"']+)(["'])/gi,
    (_, prefix, path, suffix) => `${prefix}${baseRaw}${path}${suffix}`
  );

  // Rewrite href attributes on anchors → github.com/blob for browsable links
  html = html.replace(
    /(<a[^>]*\s(?:href)=["'])(?!https?:\/\/|#|mailto:)(?:\.\/)?([^"']+)(["'])/gi,
    (_, prefix, path, suffix) => `${prefix}${baseBlob}${path}${suffix}`
  );

  return html;
}

/** Fetch README for a repo, return HTML or null if no README */
async function fetchReadmeHtml(repoName: string): Promise<string | null> {
  const url = `https://api.github.com/repos/${GITHUB_USER}/${repoName}/readme`;
  const res = await fetch(url, {
    headers: { Accept: "application/vnd.github.v3+json" },
  });

  if (res.status === 404) return null;
  if (!res.ok) {
    console.warn(`Failed to fetch README for ${repoName}: ${res.status}`);
    return null;
  }

  const data = (await res.json()) as GitHubReadmeResponse;
  const markdown = Buffer.from(data.content, "base64").toString("utf-8");
  const html = await marked(markdown);
  return rewriteRelativeUrls(html, repoName);
}

/** Escape backticks and backslashes for safe embedding in a JS template literal */
function escapeForTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main() {
  console.log(`Fetching repos for ${GITHUB_USER}...`);

  const reposRes = await fetch(
    `https://api.github.com/users/${GITHUB_USER}/repos?per_page=100&sort=updated`,
    { headers: { Accept: "application/vnd.github.v3+json" } }
  );

  if (!reposRes.ok) {
    console.error(`Failed to fetch repos: ${reposRes.status}`);
    process.exit(1);
  }

  const allRepos = (await reposRes.json()) as GitHubRepo[];
  const repos = allRepos.filter((r) => !r.fork);

  console.log(`Found ${repos.length} non-fork repos. Fetching READMEs...`);

  const projects: string[] = [];

  for (const repo of repos) {
    console.log(`  ${repo.name}...`);
    const readmeHtml = await fetchReadmeHtml(repo.name);

    const entry = `  {
    id: ${JSON.stringify(repo.name)},
    name: ${JSON.stringify(repo.name)},
    description: ${JSON.stringify(repo.description)},
    url: ${JSON.stringify(repo.html_url)},
    readmeHtml: ${readmeHtml !== null ? `\`${escapeForTemplateLiteral(readmeHtml)}\`` : "null"},
    language: ${JSON.stringify(repo.language)},
    topics: ${JSON.stringify(repo.topics)},
    archived: ${repo.archived},
    createdAt: ${JSON.stringify(repo.created_at)},
    updatedAt: ${JSON.stringify(repo.updated_at)}
  }`;

    projects.push(entry);
  }

  const output = `// AUTO-GENERATED by scripts/sync-github-projects.ts — do not edit manually
// Last synced: ${new Date().toISOString()}
import type { GitHubProject } from "@/data/models/Project";

export const githubProjects: GitHubProject[] = [
${projects.join(",\n")}
];
`;

  writeFileSync(OUTPUT_PATH, output);
  console.log(`\nWrote ${repos.length} projects to ${OUTPUT_PATH}`);
}

main();
